SUBCOMMANDS = subcommands/report subcommands/set
TRIGGERS = triggers/backup-app-export triggers/backup-app-import triggers/backup-global-export triggers/backup-global-import triggers/builder-detect triggers/builder-get-property triggers/builder-image-is-cnb triggers/builder-image-is-herokuish triggers/builder-set-property triggers/core-post-extract triggers/install triggers/post-app-clone-setup triggers/post-app-rename-setup triggers/post-delete triggers/report
BUILD = commands subcommands triggers
PLUGIN_NAME = builder

include ../../common.mk
