#!/bin/bash
set -e; 

# Check if name is specified
if [[ $1 == pg:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "/home/git/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
fi

case "$1" in

  pg:create)
    DB_IMAGE=pg/$APP
    # Check if DB container is installed
    IMAGE=$(docker images | grep "dokku/postgresql " |  awk '{print $3}')
    if [[ -z $IMAGE ]]; then
        echo "PostgreSQL image not found... Did you run 'dokku plugins-install' ?"
        exit 1
    fi
    # Check if an existing DB volume exists
    if [[ -d "/var/lib/docker/volumes/pg-$APP" ]]; then
        VOLUME="/var/lib/docker/volumes/pg-$APP/layer:/opt/postgresql"
        echo
        echo "-----> Reusing pg/$APP database"
    else
        VOLUME="/opt/postgresql"
        # Generate a random password for DB user
        DB_PASSWORD=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)
        # Temporarily store it to a file
        echo $DB_PASSWORD > "/tmp/db_pwd_$APP"
        chown git: "/tmp/db_pwd_$APP"
    fi
    # Fork DB image
    ID=$(docker run -d dokku/postgresql exit 0)
    docker wait $ID > /dev/null
    IMAGE=$(docker commit $ID)
    docker tag $IMAGE $DB_IMAGE
    # Launch container
    ID=$(docker run -v $VOLUME -p 5432 -d $DB_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD)
    sleep 4
    # Rename persistent volume
    if [[ ! -d "/var/lib/docker/volumes/pg-$APP" ]]; then
        VOLUME_PATH=$(docker inspect $ID | grep "/var/lib/docker/volumes/" | awk '{print $2}' | sed -e"s/\/layer//" | sed -e's/"//g')
        mv $VOLUME_PATH "/var/lib/docker/volumes/pg-$APP"
        sleep 1
    fi
    # Link to a potential existing app
    dokku pg:link $APP $APP
    echo
    echo "-----> PostgreSQL container created: $DB_IMAGE"
    sleep 1
    dokku pg:info $APP
    ;;

  pg:delete)
    DB_IMAGE=pg/$APP
    # Stop the container
    ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
    if [[ ! -z $ID ]]; then
        docker stop $ID
    fi
    # Remove image
    IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $1}')
    if [[ ! -z $IMAGE ]]; then
        docker rmi $IMAGE
    fi
    # Remove persistent volume
    if [[ -d "/var/lib/docker/volumes/pg-$APP" ]]; then
        rm -rf "/var/lib/docker/volumes/pg-$APP"
    fi
    echo
    echo "-----> PostgreSQL container deleted: $DB_IMAGE"
    ;;

  pg:info)
    DB_IMAGE=pg/$APP
    ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
    IP=$(docker inspect $ID | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
    PORT=$(docker port $ID 5432)
    echo
    echo "       Host: $IP"
    echo "       User: 'root'"
    if [[ -f "/tmp/db_pwd_$APP" ]]; then
        echo "       Password: '$(cat "/tmp/db_pwd_$APP")'"
    fi
    echo "       Database: 'db'"
    echo "       Public port: $PORT"
    echo
    ;;

  pg:link)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $3 ]]; then
            echo "You must specify a database name"
            exit 1
        fi
        DB_IMAGE="pg/$3"
        # Check temporarily file
    	if [[ ! -f "/tmp/db_pwd_$APP" ]]; then
            echo "Database is already linked"
            exit 1
        fi
        DB_PASSWORD=$(cat "/tmp/db_pwd_$APP")
        ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
        IP=$(docker inspect $ID | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
        # Write DATABASE_URL to app's ENV file
        URL="DATABASE_URL=postgres://root:$DB_PASSWORD@$IP/db"
        cat "/home/git/$APP/ENV" | grep "$URL" || echo "export $URL" >> "/home/git/$APP/ENV"
        echo
        echo "-----> $APP linked to $DB_IMAGE database"
        rm "/tmp/db_pwd_$APP"
    fi
    ;;

  pg:logs)
    DB_IMAGE=pg/$APP
    ID=$(docker ps -a | grep "$DB_IMAGE" |  awk '{print $1}')
    docker logs $ID | tail -n 100
    ;;

  help)
    cat && cat<<EOF
    pg:create <app>     Create a PostgreSQL container
    pg:delete <app>     Delete specified PostgreSQL container
    pg:info <app>       Display database informations
    pg:link <app> <db>  Link an app to a PostgreSQL database
    pg:logs <app>       Display last logs from PostgreSQL container
EOF
    ;;

esac
