SUBCOMMANDS = subcommands/login subcommands/report subcommands/set
TRIGGERS = triggers/install triggers/post-delete triggers/report
BUILD = commands subcommands triggers
PLUGIN_NAME = registry

include ../../common.mk
