#!/usr/bin/env bash
[[ " help builds:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
source "$PLUGIN_AVAILABLE_PATH/builds/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | builds:help)
    cmd-builds-help "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
