#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

repo_help_content_func () {
  declare desc="return repo plugin help content"
  cat<<help_content
    repo:gc <app>, Runs 'git gc --aggressive' against the application's repo
    repo:purge-cache <app>, Deletes the contents of the build cache stored in the repository
help_content
}

repo_help_cmd() {
  if [[ $1 = "repo:help" ]] ; then
    echo -e 'Usage: dokku repo[:COMMAND]'
    echo ''
    echo "Runs commands that interact with the app's repo"
    echo ''
    echo 'Additional commands:'
    repo_help_content_func | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    repo_help_content_func
  else
    cat<<help_desc
    repo, Runs commands that interact with the app's repo
help_desc
  fi
}
