SUBCOMMANDS = subcommands/gc subcommands/purge-cache subcommands/report subcommands/set
TRIGGERS = triggers/pre-delete triggers/install triggers/post-delete triggers/post-extract
BUILD = commands subcommands triggers
PLUGIN_NAME = repo

include ../../common.mk
