#!/usr/bin/env bash
set -eo pipefail
export DOKKU_ROOT=${DOKKU_ROOT:="/home/dokku"}
export PLUGIN_PATH=${PLUGIN_PATH:="/var/lib/dokku/plugins"}

[[ -f $DOKKU_ROOT/dokkurc ]] && source $DOKKU_ROOT/dokkurc

[[ $DOKKU_TRACE ]] && set -x

if [[ $(id -un) != "dokku" && $1 != "plugins-install" ]]; then
  sudo -u dokku -H $0 "$@"
  exit
fi

case "$1" in
  help)
    cat<<EOF | pluginhook commands help | sort
    help            Print the list of commands
EOF
    ;;

  *)
    for script in $(ls -d /var/lib/dokku/plugins/*/commands); do
      $script "$@"
    done
    ;;

esac
