#!/bin/bash
APP="$1"; PORT="$2"; HOSTNAME="$3"
cat<<EOF
upstream $APP { server 127.0.0.1:$PORT; }
server { 
  listen      80;
  server_name $HOSTNAME;
  location    / { proxy_pass  http://$APP; }
}
EOF