#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/common/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-railpack-backup-app-export() {
  declare desc="exports the app's builder-railpack properties into the backup scope dir"
  declare trigger="backup-app-export"
  declare APP="$1" SCOPE_DIR="$2"
  "$PLUGIN_AVAILABLE_PATH/backup/backup-property" export "builder-railpack" "$APP" "$SCOPE_DIR"
}

trigger-builder-railpack-backup-app-export "$@"
