#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-events-off() {
  declare desc="disables dokku events logger"
  declare cmd="events:off"
  [[ "$1" == "$cmd" ]] && shift 1

  echo "Disabling dokku events logger"
  rm -f "$DOKKU_ROOT/.dokkurc/DOKKU_EVENTS"
}

cmd-events-off "$@"
