#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

proxy_main_cmd() {
  declare desc="displays app proxy implementation via command line"
  local cmd="proxy"
  [[ "$1" == "$cmd" ]] && shift 1
  local APPS=$(dokku_apps)
  if [[ -n "$1" ]]; then
    local APPS="$1"
  fi

  dokku_log_warn "Deprecated: Please use proxy:report"
  dokku_col_log_info1_quiet "App Name" "Proxy Type"
  local app
  for app in $APPS; do
    verify_app_name "$app"
    dokku_col_log_msg "$app" "$(get_app_proxy_type "$app")"
  done
}

proxy_main_cmd "$@"
