#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

proxy_main_cmd() {
  local desc="displays app proxy implementation via command line"
  local cmd="proxy"
  local ALL_APPS=$(dokku_apps)
  if [[ -n "$2" ]]; then
    local APP="$2"
  fi
  local APPS=${APP:="$ALL_APPS"}

  dokku_col_log_info1_quiet "App Name" "Proxy Type"
  for app in $APPS; do
    verify_app_name "$app"
    dokku_col_log_msg "$app" "$(get_app_proxy_type "$app")"
  done
}

proxy_main_cmd "$@"
