#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

cmd-proxy-enable() {
  declare desc="enable proxy for app via command line"
  declare cmd="proxy:enable"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  if [[ "$(is_app_proxy_enabled "$APP")" == "false" ]]; then
    dokku_log_info1 "Enabling proxy for app ($APP)"
    [[ "$2" == "--no-restart" ]] && local CONFIG_SET_ARGS=$2
    # shellcheck disable=SC2086
    DOKKU_QUIET_OUTPUT=1 config_unset $CONFIG_SET_ARGS $APP DOKKU_DISABLE_PROXY
    plugn trigger proxy-enable "$APP"
  else
    dokku_log_info1 "proxy is already enabled for app ($APP)"
  fi
}

cmd-proxy-enable "$2" --no-restart
