#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

proxy_ports_set_cmd() {
  declare desc="set proxy port mappings for an app"
  local cmd="proxy:set"
  local APP="$2"
  verify_app_name "$APP"
  shift 2

  set_proxy_ports "$APP" "$@"
  plugn trigger post-proxy-ports-update "$APP" "set"
}

proxy_ports_set_cmd "$@"
