#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

cmd-proxy-ports-set() {
  declare desc="set proxy port mappings for an app"
  declare cmd="proxy:set"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  verify_app_name "$APP"
  shift 1

  set_proxy_ports "$APP" "$@"
  plugn trigger post-proxy-ports-update "$APP" "set"
}

cmd-proxy-ports-set "$@"
