#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

cmd-proxy-ports() {
  declare desc="cmd wrapper to list proxy port mappings for an app"
  declare cmd="proxy:ports"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  verify_app_name "$APP"
  list_app_proxy_ports "$APP"
}

cmd-proxy-ports "$@"
