#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

cmd-proxy-ports-clear() {
  declare desc="clear all proxy port mappings for an app"
  declare cmd="proxy:clear"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  verify_app_name "$APP"
  DOKKU_QUIET_OUTPUT=1 config_unset --no-restart "$APP" DOKKU_PROXY_PORT_MAP
  plugn trigger post-proxy-ports-update "$APP" "clear"
}

cmd-proxy-ports-clear "$@"
