#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

proxy_ports_add_cmd() {
  declare desc="add proxy port mappings from an app"
  local cmd="proxy:add"
  local APP="$2"
  verify_app_name "$APP"
  shift 2

  add_proxy_ports "$APP" "$@"
  plugn trigger post-proxy-ports-update "$APP" "add"
}

proxy_ports_add_cmd "$@"
