#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

proxy_ports_clear_cmd() {
  declare desc="clear all proxy port mappings for an app"
  local cmd="proxy:clear"
  local APP="$2"
  verify_app_name "$APP"

  config_unset --no-restart "$APP" DOKKU_PROXY_PORT_MAP
  plugn trigger post-proxy-ports-update "$APP" "clear"
}

proxy_ports_clear_cmd "$@"
