#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

cmd-proxy-ports-remove() {
  declare desc="remove specific proxy port mappings from an app"
  local cmd="proxy:ports-remove"
  local APP="$2"
  verify_app_name "$APP"
  shift 2

  local INPUT_PORTS="$*"
  if [[ -z "$INPUT_PORTS" ]]; then
    dokku_log_warn "No port mapping specified. Please supply a valid configured host port"
    list_app_proxy_ports "$APP"
    dokku_log_fail "exiting..."
  fi

  remove_proxy_ports "$APP" "$@"
  plugn trigger post-proxy-ports-update "$APP" "remove"
}

cmd-proxy-ports-remove "$@"
