#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

cmd-proxy-ports-add() {
  declare desc="add proxy port mappings to an app"
  declare cmd="proxy:add"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  verify_app_name "$APP"
  shift 1

  add_proxy_ports "$APP" "$@"
  plugn trigger post-proxy-ports-update "$APP" "add"
}

cmd-proxy-ports-add "$@"
