#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

proxy_set_cmd() {
  declare desc="enable proxy for app via command line"
  local cmd="proxy:set"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"

  local APP="$2"; verify_app_name "$APP"
  dokku_log_info1 "proxy:set not implemented"
}

proxy_set_cmd "$@"
