#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

cmd-proxy-set() {
  declare desc="enable proxy for app via command line"
  declare cmd="proxy:set"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1" PROXY_TYPE="$2"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  if [[ -n "$PROXY_TYPE" ]]; then
    DOKKU_QUIET_OUTPUT=1 config_set --no-restart "$APP" DOKKU_APP_PROXY_TYPE="$PROXY_TYPE"
  else
    dokku_log_fail "Please specify a proxy type!"
  fi
}

cmd-proxy-set "$@"
