#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

proxy_set_cmd() {
  declare desc="enable proxy for app via command line"
  local cmd="proxy:set"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"

  local APP="$2"
  verify_app_name "$APP"
  local PROXY_TYPE="$3"

  if [[ -n "$PROXY_TYPE" ]]; then
    config_set --no-restart "$APP" DOKKU_APP_PROXY_TYPE="$PROXY_TYPE"
  else
    dokku_log_fail "Please specify a proxy type!"
  fi
}

proxy_set_cmd "$@"
