#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-storage-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="storage"
  local plugin_description="Manage mounted volumes"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    storage:ensure-directory [--chown option] <directory>, Creates a persistent storage directory in the recommended storage path
    storage:list <app> [--format text|json], List bind mounts for app's container(s) (host:container)
    storage:mount <app> <host-dir:container-dir>, Create a new bind mount
    storage:report [<app>] [<flag>], Displays a checks report for one or more apps
    storage:unmount <app> <host-dir:container-dir>, Remove an existing bind mount
help_content
}
