GOARCH ?= amd64
SUBCOMMANDS = subcommands/default subcommands/create subcommands/destroy subcommands/ensure-directory subcommands/info subcommands/list subcommands/list-entries subcommands/mount subcommands/report subcommands/unmount
TRIGGERS = triggers/install triggers/storage-list
BUILD = commands subcommands triggers
PLUGIN_NAME = storage

include ../../common.mk
