#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/internal-functions"

cmd-nginx-report() {
  declare desc="displays a nginx report for one or more apps"
  declare cmd="nginx:report"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1" INFO_FLAG="$2"

  if [[ -n "$APP" ]] && [[ "$APP" == --* ]]; then
    INFO_FLAG="$APP"
    APP=""
  fi

  if [[ -z "$APP" ]] && [[ -z "$INFO_FLAG" ]]; then
    INFO_FLAG="true"
  fi

  if [[ -z "$APP" ]]; then
    for app in $(dokku_apps); do
      cmd-nginx-report-single "$app" "$INFO_FLAG" | tee || true
    done
  else
    cmd-nginx-report-single "$APP" "$INFO_FLAG"
  fi
}

cmd-nginx-report-single() {
  declare APP="$1" INFO_FLAG="$2"
  if [[ "$INFO_FLAG" == "true" ]]; then
    INFO_FLAG=""
  fi
  verify_app_name "$APP"
  local flag_map=(
    "--nginx-access-log-format: $(fn-nginx-access-log-format "$APP")"
    "--nginx-access-log-path: $(fn-nginx-access-log-path "$APP")"
    "--nginx-bind-address-ipv4: $(fn-nginx-bind-address-ipv4 "$APP")"
    "--nginx-bind-address-ipv6: $(fn-nginx-bind-address-ipv6 "$APP")"
    "--nginx-client-max-body-size: $(fn-nginx-client-max-body-size "$APP")"
    "--nginx-disable-custom-config: $(fn-plugin-property-get-default "nginx" "$APP" "disable-custom-config" "false")"
    "--nginx-error-log-path: $(fn-nginx-error-log-path "$APP")"
    "--nginx-global-hsts: $(fn-plugin-property-get-default "nginx" "--global" "hsts" "true")"
    "--nginx-computed-hsts: $(fn-nginx-hsts-is-enabled "$APP")"
    "--nginx-hsts: $(fn-plugin-property-get-default "nginx" "$APP" "hsts" "")"
    "--nginx-hsts-include-subdomains: $(fn-nginx-hsts-include-subdomains "$APP")"
    "--nginx-hsts-max-age: $(fn-nginx-hsts-max-age "$APP")"
    "--nginx-hsts-preload: $(fn-nginx-hsts-preload "$APP")"
    "--nginx-computed-nginx-conf-sigil-path: $(fn-nginx-computed-nginx-conf-sigil-path "$APP")"
    "--nginx-global-nginx-conf-sigil-path: $(fn-nginx-global-nginx-conf-sigil-path)"
    "--nginx-nginx-conf-sigil-path: $(fn-nginx-nginx-conf-sigil-path "$APP")"
    "--nginx-proxy-buffer-size: $(fn-nginx-proxy-buffer-size "$APP")"
    "--nginx-proxy-buffering: $(fn-nginx-proxy-buffering "$APP")"
    "--nginx-proxy-buffers: $(fn-nginx-proxy-buffers "$APP")"
    "--nginx-proxy-busy-buffers-size: $(fn-nginx-proxy-busy-buffers-size "$APP")"
    "--nginx-proxy-read-timeout: $(fn-nginx-proxy-read-timeout "$APP")"
    "--nginx-last-visited-at: $(fn-nginx-vhosts-last-visited-at "$APP")"
    "--nginx-x-forwarded-for-value: $(fn-nginx-x-forwarded-for-value "$APP")"
    "--nginx-x-forwarded-port-value: $(fn-nginx-x-forwarded-port-value "$APP")"
    "--nginx-x-forwarded-proto-value: $(fn-nginx-x-forwarded-proto-value "$APP")"
    "--nginx-x-forwarded-ssl: $(fn-nginx-x-forwarded-ssl "$APP")"
  )

  if [[ -z "$INFO_FLAG" ]]; then
    dokku_log_info2_quiet "${APP} nginx information"
    for flag in "${flag_map[@]}"; do
      key="$(echo "${flag#--}" | cut -f1 -d' ' | tr - ' ')"
      dokku_log_verbose "$(printf "%-30s %-25s" "${key^}" "${flag#*: }")"
    done
  else
    local match=false
    local value_exists=false
    for flag in "${flag_map[@]}"; do
      valid_flags="${valid_flags} $(echo "$flag" | cut -d':' -f1)"
      if [[ "$flag" == "${INFO_FLAG}:"* ]]; then
        value=${flag#*: }
        size="${#value}"
        if [[ "$size" -ne 0 ]]; then
          echo "$value" && match=true && value_exists=true
        else
          match=true
        fi
      fi
    done
    [[ "$match" == "true" ]] || dokku_log_fail "Invalid flag passed, valid flags:${valid_flags}"
    [[ "$value_exists" == "true" ]] || dokku_log_fail "not deployed"
  fi
}

cmd-nginx-show-config() {
  declare desc="display app nginx config"
  declare cmd="nginx:show-config"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  verify_app_name "$APP"
  if [[ ! -f "$DOKKU_ROOT/$APP/nginx.conf" ]]; then
    dokku_log_fail "No nginx.conf exists for $APP"
  fi

  cat "$DOKKU_ROOT/$APP/nginx.conf"
}

cmd-nginx-start() {
  declare desc="starts the nginx server"
  declare cmd="nginx:start"
  [[ "$1" == "$cmd" ]] && shift 1

  fn-plugin-property-write "nginx" "--global" "proxy-status" "started"
  fn-nginx-vhosts-nginx-init-cmd "enable"
  fn-nginx-vhosts-nginx-init-cmd "start"
}

cmd-nginx-stop() {
  declare desc="stops the nginx server"
  declare cmd="nginx:stop"
  [[ "$1" == "$cmd" ]] && shift 1

  fn-plugin-property-write "nginx" "--global" "proxy-status" "stopped"
  fn-nginx-vhosts-nginx-init-cmd "stop"
  fn-nginx-vhosts-nginx-init-cmd "disable"
}

cmd-nginx-validate-config() {
  declare desc="validates and optionally cleans up invalid nginx configurations"
  declare cmd="nginx:validate-config"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1" FLAG="$2"

  validate_nginx "$APP" "$FLAG"
}
