#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

trigger-nginx-vhosts-core-post-deploy() {
  declare desc="nginx-vhosts core-post-deploy plugin trigger"
  declare trigger="nginx_core_post_deploy"
  declare APP="$1"
  local HAS_NETWORK_CONFIG

  if [[ "$(plugn trigger proxy-type "$APP")" != "nginx" ]]; then
    return
  fi

  HAS_NETWORK_CONFIG="$(plugn trigger network-config-exists "$APP")"
  if [[ "$HAS_NETWORK_CONFIG" == "true" ]]; then
    if [[ "$(is_app_vhost_enabled "$APP")" == "false" ]]; then
      dokku_log_info1 "VHOST support disabled. Skipping domains setup"
    elif [[ ! -f "$DOKKU_ROOT/$APP/VHOST" ]]; then
      domains_setup "$APP"
    fi

    nginx_build_config "$APP"
  fi
}

trigger-nginx-vhosts-core-post-deploy "$@"
