#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

trigger-nginx-vhosts-post-delete() {
  declare desc="nginx-vhosts post-delete trigger"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "nginx" "$APP"
  restart_nginx "$@" >/dev/null
}

trigger-nginx-vhosts-post-delete "$@"
