#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

case "$DOKKU_DISTRO" in
  debian)
    sudo /usr/sbin/invoke-rc.d nginx reload > /dev/null
    ;;

  ubuntu)
    sudo /etc/init.d/nginx reload > /dev/null
    ;;

  opensuse)
    sudo /sbin/service nginx reload > /dev/null
    ;;
esac
