#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/internal-functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

trigger-nginx-vhosts-post-app-rename-setup() {
  declare desc="calls proxy-clear-config"
  declare trigger="post-app-rename-setup"
  declare OLD_APP="$1" NEW_APP="$2"

  plugn trigger proxy-clear-config "$NEW_APP"
}

trigger-nginx-vhosts-post-app-rename-setup "$@"
