#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

APP="$1"
NO_VHOST=$(dokku config:get $APP NO_VHOST || true)

if [[ -n "$NO_VHOST" ]]; then
  dokku_log_info1 "NO_VHOST config detected"
elif [[ ! -f "$DOKKU_ROOT/$APP/VHOST" ]]; then
  dokku domains:setup $APP
fi

dokku nginx:build-config $APP
