#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

trigger-nginx-vhosts-pre-disable-vhost() {
  declare desc="unset port prior to vhosts being disabled"
  declare trigger="pre-disable-vhost"
  declare APP="$1"

  if [[ "$(plugn trigger proxy-type "$APP")" != "nginx" ]]; then
    return
  fi

  # only clear ports if they are port 80 or 443
  local PROXY_PORT=$(plugn trigger ports-get-property "$APP" "proxy-port")
  local PROXY_SSL_PORT=$(plugn trigger ports-get-property "$APP" "proxy-ssl-port")

  if [[ "$PROXY_PORT" == "80" ]]; then
    fn-plugin-property-delete "proxy" "$APP" "proxy-port"
  fi
  if [[ "$PROXY_SSL_PORT" == "443" ]]; then
    fn-plugin-property-delete "proxy" "$APP" "proxy-ssl-port"
  fi

  # clear ports if there is a mapping starting with http:80 or https:443
  local PORT_MAPS=$(plugn trigger ports-get "$APP")
  for PORT_MAP in $PORT_MAPS; do
    if [[ "$PORT_MAP" == "http:80:"* ]] || [[ "$PORT_MAP" == "https:443:"* ]]; then
      plugn trigger ports-clear "$APP"
      break
    fi
  done
}

trigger-nginx-vhosts-pre-disable-vhost "$@"
