#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

trigger-nginx-vhosts-pre-enable-vhost() {
  declare desc="unset port prior to vhosts being enabled"
  declare trigger="pre-enable-vhost"
  declare APP="$1"

  if [[ "$(get_app_proxy_type "$APP")" == "nginx" ]]; then
    DOKKU_QUIET_OUTPUT=1 config_unset --no-restart "$APP" DOKKU_PROXY_PORT DOKKU_PROXY_SSL_PORT DOKKU_PROXY_PORT_MAP
  fi
}

trigger-nginx-vhosts-pre-enable-vhost "$@"
