#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

trigger-nginx-vhosts-proxy-enable() {
  declare desc="enable nginx proxy"
  declare trigger="proxy-enable"
  declare APP="$1"

  verify_app_name "$APP"
  if [[ "$(plugn trigger proxy-type "$APP")" == "nginx" ]]; then
    enable_app_vhost "$APP" --no-restart
    ps_restart "$APP"
  fi
}

trigger-nginx-vhosts-proxy-enable "$@"
