#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

trigger-nginx-vhosts-proxy-supports-routes() {
  declare desc="advertises path-based routing support for nginx"
  declare trigger="proxy-supports-routes"
  declare APP="$1"

  if [[ "$(plugn trigger proxy-type "$APP")" != "nginx" ]]; then
    return
  fi

  echo "true"
}

trigger-nginx-vhosts-proxy-supports-routes "$@"
