#!/usr/bin/env bash
set -eo pipefail
SELF=`which $0`; APP="$1"; TARGET="$2"; FORWARDED_PORT="$3"
TMP=$(mktemp -d -t "$TARGET.XXXXX")
trap "rm -rf $TMP" EXIT
rmdir $TMP && cp -r $(dirname $SELF)/$APP $TMP
cd $TMP
git init
git config user.email "robot@example.com"
git config user.name "Test Robot"
git add .
git commit -m 'initial commit'
REPO="test-$(basename $APP)-$RANDOM"
git remote add target dokku@$TARGET:$REPO
git push target master
# Obtaining the URL of the app through `dokku url` currently hangs the script
# since issues with pluginhook require a CTRL-C to exit out of ssh at the end.
# For now, we fix by adding an echo in front (see #272).
URL=$(echo | ssh dokku@$TARGET url $REPO)$FORWARDED_PORT
sleep 2
echo "-----> Checking for deployed app at: $URL"
./check_deploy $URL && echo "-----> Deploy success!" || {
  printf '.'; sleep 4
  ./check_deploy $URL && echo "-----> Deploy success!"
}
