#!/usr/bin/env bash
# help:<app> KEY:Display a config value for an app
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source $PLUGIN_ROOT/config-common.sh

if [[ -z $2 ]]; then
  echo "Usage: dokku $DOKKU_ORIGINAL_COMMAND APP KEY"
  echo "Must specify KEY."
  exit 1
fi

if [ ! -f $ENV_FILE ] || [ ! -s $ENV_FILE ] ; then
  exit 1
fi

KEY="$2"

cat $ENV_FILE | grep -Eo "export ([a-zA-Z_][a-zA-Z0-9_]*=.*)" | cut -d" " -f2 | grep "^$KEY=" | cut -d"=" -f2-


