#!/usr/bin/env bash
# help:<app> KEY1=VALUE1 [KEY2=VALUE2 ...]:Set one or more config vars
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source $PLUGIN_ROOT/config-common.sh

if [[ -z "${*:2}" ]]; then
  echo "Usage: dokku $DOKKU_ORIGINAL_COMMAND APP KEY1=VALUE1 [KEY2=VALUE2 ...]"
  echo "Must specify KEY and VALUE to set."
  exit 1
fi

ENV_ADD=""
ENV_TEMP=`cat "${ENV_FILE}"`
ID=$(< "$APP_DIR/CONTAINER")
RESTART=false
VARS="${*:2}"

for var in $VARS; do
  if [[ $var != *"="* ]]; then
    echo "Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]"
    echo "Must specify KEY and VALUE to set."
    exit 1
  fi
done

for var in $VARS; do
  KEY=`echo ${var} | cut -d"=" -f1`
  VALUE=`echo ${var} | cut -d"=" -f2-`

  if [[ $KEY == [a-zA-Z_][a-zA-Z0-9_]* ]]; then
    RESTART_APP=true
    ENV_TEMP=$(echo -e "${ENV_TEMP}" | sed "/^export $KEY=/ d")
    ENV_TEMP="${ENV_TEMP}\nexport ${var}"
    ENV_ADD=$(echo -e "${ENV_ADD}" | sed "/^$KEY=/ d")
    ENV_ADD="${ENV_ADD}\n${var}"
  fi
done

if [ $RESTART_APP ]; then
  echo "-----> Setting config vars and restarting $APP"
  config_styled_hash "$ENV_ADD"

  echo -e "$ENV_TEMP" | sed '/^$/d' | sort > $ENV_FILE
  config_restart_app $APP
fi



