#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-ssh-keys-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="ssh-keys"
  local plugin_description="Manage public ssh keys used for deployment"

  if [[ "$CMD" == "$plugin_name:help" ]]; then
    echo -e "Usage: dokku $plugin_name[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    ssh-keys:list [--format text|json] [<name>], List of all authorized dokku public ssh keys
    ssh-keys:add <name> [/path/to/key], Add a new public key by pipe or path
    ssh-keys:remove [--fingerprint fingerprint|<name>], Remove SSH public key by name
help_content
}
