#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

ssh_keys_help_content_func() {
  declare desc="return ssh-keys plugin help content"
  cat <<help_content
    ssh-keys:list, List of all authorized dokku public ssh keys
    ssh-keys:add <name> [/path/to/key], Add a new public key by pipe or path
    ssh-keys:remove <name>, Remove SSH public key by name
help_content
}

cmd-ssh-keys-help() {
  if [[ $1 == "ssh-keys:help" ]]; then
    echo -e 'Usage: dokku ssh-keys[:COMMAND]'
    echo ''
    echo 'Manage public ssh keys that are allowed to connect to Dokku'
    echo ''
    echo 'Additional commands:'
    ssh_keys_help_content_func | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    ssh_keys_help_content_func
  else
    cat <<help_desc
    ssh-keys, Manage public ssh keys that are allowed to connect to Dokku
help_desc
  fi
}


cmd-list-ssh-keys() {
  declare desc="List ssh key hashes"
  local cmd="ssh-keys:list"
  verify_ssh_key_file
  sshcommand list dokku
}
