#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-list-ssh-keys() {
  declare desc="List ssh key hashes"
  local cmd="ssh-keys:list"
  verify_ssh_key_file
  sshcommand list dokku
}
