#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-list-ssh-keys() {
  declare desc="List ssh key hashes"
  declare cmd="ssh-keys:list"
  [[ "$1" == "$cmd" ]] && shift 1

  verify_ssh_key_file
  sshcommand list dokku
}
