#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/config/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-lambda-builder-detect() {
  declare desc="builder-lambda builder-detect plugin trigger"
  declare trigger="builder-detect"
  declare APP="$1" SOURCECODE_WORK_DIR="$2"
  local ARCHITECTURE="$(dpkg --print-architecture 2>/dev/null || true)"

  if [[ "$ARCHITECTURE" == "armhf" ]]; then
    return
  fi

  if [[ -f "$SOURCECODE_WORK_DIR/lambda.yml" ]]; then
    echo "lambda"
    return
  fi
}

trigger-builder-lambda-builder-detect "$@"
