#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-lambda-install() {
  declare desc="installs the builder-lambda plugin"
  declare trigger="install"

  fn-plugin-property-setup "builder-lambda"

  mkdir -p "${DOKKU_LIB_ROOT}/data/builder-lambda"
  chown -R "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "${DOKKU_LIB_ROOT}/data/builder-lambda"
}

trigger-builder-lambda-install "$@"
