#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-lambda-post-create() {
  declare desc="builder-lambda post-create plugin trigger"
  declare trigger="post-create"
  declare APP="$1"

  "$PLUGIN_CORE_AVAILABLE_PATH/common/common" --quiet create-data-directory "builder-lambda" "$APP"
}

trigger-builder-lambda-post-create "$@"
