#!/bin/bash

exec >>/var/log/services/dokku-restore
exec 2>&1

if [[ "$1" -ne 0 ]]; then
  echo "Error restoring dokku apps! Retrying in 30 seconds..."
  exec sleep 30
  exit 0
fi

echo "Done restoring dokku apps."

while ! (echo >/dev/tcp/127.0.0.1/22) >/dev/null 2>&1; do sleep 1; done
while ! (echo >/dev/tcp/127.0.0.1/80) >/dev/null 2>&1; do sleep 1; done
touch /var/run/dokku/ready
echo "Dokku is ready."

exec sleep infinity
