#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

domains_add_global_cmd() {
  declare desc="add global domain names via command line"
  local cmd="domains:add-global"
  [[ -z $2 ]] && dokku_log_fail "Please specify a domain name. Usage: dokku $1 <domain> [<domain> ...]"

  shift 1
  domains_add_global "$@"
}

domains_add_global_cmd "$@"
