#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

cmd-domains-clear() {
  declare desc="clear all app domains"
  local cmd="domains:clear"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$2"
  local APP="$2"
  local APP_VHOST_PATH="$DOKKU_ROOT/$APP/VHOST"

  rm -f "$APP_VHOST_PATH"
  domains_setup "$APP"
  plugn trigger post-domains-update "$APP" "clear"
  dokku_log_info1 "Cleared domains in $APP"
}

cmd-domains-clear "$@"
