#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

cmd-domains-clear() {
  declare desc="clear all app domains"
  declare cmd="domains:clear"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  [[ "$APP" == "--all" ]] || verify_app_name "$APP"
  fn-domains-clear "$APP"
}

cmd-domains-clear "$@"
