#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

domains_enable_cmd() {
  declare desc="enable domains/VHOST support via command line"
  local cmd="domains:enable"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  domains_enable "$2"
}

domains_enable_cmd "$@"
