#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

cmd-domains-remove() {
  declare desc="removes domains from app via command line"
  declare cmd="domains:remove"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1" DOMAIN_NAME="$2"

  [[ -z "$DOMAIN_NAME" ]] && dokku_log_fail "Please specify a domain name. Usage: dokku $1 $2 <domain> [<domain> ...]"
  verify_app_name "$APP"
  domains_remove "$@"
}

cmd-domains-remove "$@"
