#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/../functions"

[[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
verify_app_name "$2"
APP="$2"

if [[ -z $3 ]]; then
  echo "Usage: dokku $1 $2 DOMAIN"
  echo "Must specify DOMAIN."
  exit 1
fi

dokku domains:setup $APP
sed -i "/^$3$/d" "$DOKKU_ROOT/$APP/VHOST"
pluginhook post-domains-update $APP
dokku_log_info1 "Removed $3 from $APP"
