#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

cmd-domains-remove-global() {
  declare desc="remove global domain names via command line"
  declare cmd="domains:remove-global"
  [[ "$1" == "$cmd" ]] && shift 1
  declare DOMAIN_NAME="$1"

  [[ -z "$DOMAIN_NAME" ]] && dokku_log_fail "Please specify a domain name. Usage: dokku $1 <domain> [<domain> ...]"
  domains_remove_global "$@"
}

cmd-domains-remove-global "$@"
