#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

cmd-domains-set-global() {
  declare desc="set global domain names via command line"
  declare cmd="domains:set-global"
  [[ "$1" == "$cmd" ]] && shift 1
  declare DOMAIN_NAME="$1"

  [[ -z "$DOMAIN_NAME" ]] && dokku_log_fail "Please specify a domain name. Usage: dokku $1 <domain> [<domain> ...]"
  domains_set_global "$@"
}

cmd-domains-set-global "$@"
