#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

cmd-domains-setup() {
  declare desc="setup domains to default state via command line"
  local cmd="domains:setup"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  domains_setup "$2"
}

cmd-domains-setup "$@"
