#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/../functions"

[[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
verify_app_name "$2"
APP="$2"; VHOST_PATH="$DOKKU_ROOT/$APP/VHOST"

if [[ ! -f $VHOST_PATH ]]; then
  if [[ -f "$DOKKU_ROOT/VHOST" ]];then
    VHOST=$(< "$DOKKU_ROOT/VHOST")
  else
    VHOST=$(< "$DOKKU_ROOT/HOSTNAME")
  fi
  if [[ "$VHOST" =~ $RE_IPV4 ]] || [[ "$VHOST" =~ $RE_IPV6 ]];then
    echo "unsupported vhost config found. disabling vhost support"
    [[ ! $(grep -q NO_VHOST "$DOKKU_ROOT/$APP/ENV") ]] && echo "export NO_VHOST='1'" >> "$DOKKU_ROOT/$APP/ENV"
  else
    if [[ -f "$DOKKU_ROOT/VHOST" ]]; then
      dokku_log_info1 "Creating new $VHOST_PATH..."
      SUBDOMAIN=${APP/%\.${VHOST}/}
      hostname=$(: | pluginhook nginx-hostname $APP $SUBDOMAIN $VHOST)
      if [[ ! -n $hostname ]]; then
        if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
          hostname="${APP/\//-}"
        else
          hostname="${APP/\//-}.$VHOST"
        fi
      fi

      echo "$hostname" > $VHOST_PATH
    fi
  fi
fi
