#!/usr/bin/env bash
[[ " help network:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
source "$PLUGIN_AVAILABLE_PATH/network/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | network:help)
    network_help_cmd "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
