#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-cleanup() {
  declare desc="cleans up old deployment cruft"
  declare cmd="cleanup"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  if [[ -z "$APP" ]]; then
    APP="--global"
  fi

  [[ "$APP" == "--global" ]] || verify_app_name "$APP"

  docker_cleanup "$APP" "true"
}

cmd-cleanup "$@"
