#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

dokku_run_cmd() {
  declare desc="runs command in container based on app image"
  plugn trigger scheduler-container-run "$@"
}

dokku_run_cmd "$@"
