#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-urls() {
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  local APP="$2"

  get_app_urls "$@"
}

cmd-urls "$@"
