#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-urls() {
  declare desc="reports dokku vitals for troubleshooting"
  declare cmd="url"
  declare APP="$2"

  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"

  get_app_urls "$@"
}

cmd-urls "$@"
