#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

dokku_version_cmd() {
  declare desc="prints dokku version"
  local cmd="version"
  cat "$DOKKU_ROOT/VERSION" || dokku_log_fail "Unable to determine dokku's version"
}

dokku_version_cmd "$@"
