#!/bin/bash
set -eo pipefail

echo '--> Enable and configure UFW'
sed -e 's|DEFAULT_FORWARD_POLICY=.*|DEFAULT_FORWARD_POLICY="ACCEPT"|g' \
  -i /etc/default/ufw

ufw allow ssh
ufw allow http
ufw allow https
ufw allow 2375/tcp
ufw allow 2376/tcp
