#!/bin/bash
set -eo pipefail

echo '--> Cleaning up'
rm -rf /tmp/* /var/tmp/*
history -c
cat /dev/null > /root/.bash_history
unset HISTFILE
apt-get -y autoremove
apt-get -y autoclean
rm -rf /var/lib/cloud/instances/*

echo '--> Removing keys'
rm -f /root/.ssh/authorized_keys /etc/ssh/*key*

echo '--> Clearing log files'
find /var/log -mtime -1 -type f -exec truncate -s 0 {} \;
rm -rf /var/log/*.gz /var/log/*.[0-9] /var/log/*-????????
cat /dev/null > /var/log/lastlog; cat /dev/null > /var/log/wtmp
