#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
case "$1" in
  run)
    if [[ -z $2 ]]; then
        echo "Please specify an app to run the command on"
        exit 1
    fi
    APP="$2"; IMAGE="app/$APP"
    if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
        echo "App $APP does not exist"
        exit 1
    fi
    shift 2

    DOCKER_ARGS=$(: | pluginhook docker-args $APP)
    docker run -i -t $DOCKER_ARGS $IMAGE /exec "$@"
    ;;

  help)
    cat && cat<<EOF
    run <app> <cmd>                                 Run a command in the environment of an application
EOF
    ;;

esac

