#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help)
    cat && cat<<EOF
    backup:export [file]                            Export dokku configuration files
    backup:import [file]                            Import dokku configuration files
EOF
    ;;

esac

