SUBCOMMANDS = subcommands/report subcommands/set
TRIGGERS = triggers/install triggers/post-delete triggers/post-deploy triggers/pre-deploy
BUILD = commands subcommands triggers
PLUGIN_NAME = app-json

include ../../common.mk
