#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/app-json/internal-functions"

trigger-app-json-post-deploy() {
  declare desc="app-json scripts execution"
  declare trigger="post-deploy"
  declare APP="$1" IMAGE_TAG="$4"
  local PHASE_SCRIPT_KEY="postdeploy"

  execute_script "$APP" "$IMAGE_TAG" "$PHASE_SCRIPT_KEY"
}

trigger-app-json-post-deploy "$@"
