#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/app-json/internal-functions"

app_json_post_deploy() {
  declare desc="app-json scripts execution"
  local trigger="app_json_post_deploy"
  local APP="$1"
  local IMAGE_TAG="$4"
  local PHASE_SCRIPT_KEY="postdeploy"

  dokku_log_info1 "Attempting to run scripts.dokku.$PHASE_SCRIPT_KEY from app.json (if defined)"
  execute_script "$APP" "$IMAGE_TAG" "$PHASE_SCRIPT_KEY"
}

app_json_post_deploy "$@"
