#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/common/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-traefik-backup-global-export() {
  declare desc="exports the global traefik properties into the backup scope dir"
  declare trigger="backup-global-export"
  declare SCOPE_DIR="$1"
  "$PLUGIN_AVAILABLE_PATH/backup/backup-property" export "traefik" "--global" "$SCOPE_DIR"
}

trigger-traefik-backup-global-export "$@"
