#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/common/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-traefik-backup-global-import() {
  declare desc="restores the global traefik properties from the backup scope dir"
  declare trigger="backup-global-import"
  declare SCOPE_DIR="$1"
  "$PLUGIN_AVAILABLE_PATH/backup/backup-property" import "traefik" "--global" "$SCOPE_DIR"
}

trigger-traefik-backup-global-import "$@"
