#!/usr/bin/env bash
[[ " traefik:help help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
source "$PLUGIN_AVAILABLE_PATH/traefik-vhosts/help-functions"
source "$PLUGIN_AVAILABLE_PATH/traefik-vhosts/command-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | traefik:help)
    cmd-traefik-help "$@"
    ;;

  traefik:label:add)
    cmd-traefik-label-add "$@"
    ;;

  traefik:label:remove)
    cmd-traefik-label-remove "$@"
    ;;

  traefik:label:show)
    cmd-traefik-label-show "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac
