#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-traefik-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="traefik"
  local plugin_description="Manage mounted volumes"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    traefik:report [<app>] [<flag>], Displays an traefik report for one or more apps
    traefik:set <app> <property> (<value>), Set or clear an traefik property for an app
    traefik:show-config <app>, Display traefik compose config
    traefik:start, Starts the traefik server
    traefik:stop, Stops the traefik server
help_content
}
