#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-traefik-install() {
  declare desc="installs the traefik plugin"
  declare trigger="install"

  fn-plugin-property-setup "traefik"
  "$PLUGIN_CORE_AVAILABLE_PATH/common/common" --quiet setup-data-directory "traefik-vhosts"
}

trigger-traefik-install "$@"
