#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-traefik-install() {
  declare desc="installs the traefik plugin"
  declare trigger="install"

  mkdir -p "${DOKKU_LIB_ROOT}/data/traefik"
  chown -R "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "${DOKKU_LIB_ROOT}/data/traefik"

  fn-plugin-property-setup "traefik"
}

trigger-traefik-install "$@"
