#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-traefik-vhosts-post-create() {
  declare desc="traefik-vhosts post-create trigger"
  declare trigger="post-create"
  declare APP="$1"

  fn-plugin-property-setup-app "traefik" "$APP"
}

trigger-traefik-vhosts-post-create "$@"
