#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-traefik-vhosts-post-delete() {
  declare desc="traefik-vhosts post-delete trigger"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "traefik" "$APP"
  "$PLUGIN_CORE_AVAILABLE_PATH/common/common" --quiet migrate-data-directory "traefik-vhosts" "$APP"
}

trigger-traefik-vhosts-post-delete "$@"
