#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

trigger-scheduler-k3s-proxy-supports-routes() {
  declare desc="advertises path-based routing support for k3s"
  declare trigger="proxy-supports-routes"
  declare APP="$1"

  if [[ "$(plugn trigger proxy-type "$APP")" != "k3s" ]]; then
    return
  fi

  echo "true"
}

trigger-scheduler-k3s-proxy-supports-routes "$@"
