#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

cmd-logs-failed() {
  declare desc="shows the last failed deploy logs for an app"
  declare cmd="logs:failed" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  local DOKKU_SCHEDULER
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"

  DOKKU_SCHEDULER=$(config_get "$APP" DOKKU_SCHEDULER || echo "docker-local")
  plugn trigger scheduler-failed "$DOKKU_SCHEDULER" "$APP"
}

cmd-logs-failed "$@"
