#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/functions"

[[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
verify_app_name "$2"
APP="$2"

config_create
[[ ! -s $ENV_FILE ]] && echo "$APP has no config vars" && exit 1

VARS=$(grep -Eo "export ([a-zA-Z_][a-zA-Z0-9_]*=.*)" $ENV_FILE | cut -d" " -f2-)

for var in "$@"; do
  if [[ "$var" == "--shell" ]]; then
    echo $VARS
    exit 0
  fi
done

dokku_log_info2_quiet "$APP config vars"
config_styled_hash "$VARS"
