#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-caddy-install() {
  declare desc="installs the caddy plugin"
  declare trigger="install"

  fn-plugin-property-setup "caddy"
  "$PLUGIN_CORE_AVAILABLE_PATH/common/common" --quiet setup-data-directory "caddy"
}

trigger-caddy-install "$@"
