#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-caddy-vhosts-post-delete() {
  declare desc="destroys the caddy-vhosts properties for a given app"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "caddy-vhosts" "$APP"
  "$PLUGIN_CORE_AVAILABLE_PATH/common/common" --quiet migrate-data-directory "caddy-vhosts" "$APP"
}

trigger-caddy-vhosts-post-delete "$@"
