#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-caddy-vhosts-post-delete() {
  declare desc="caddy-vhosts post-delete trigger"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "caddy" "$APP"
}

trigger-caddy-vhosts-post-delete "$@"
