SUBCOMMANDS = subcommands/report subcommands/set
TRIGGERS = triggers/scheduler-detect triggers/install triggers/post-app-clone-setup triggers/post-app-rename-setup triggers/post-delete triggers/report
BUILD = commands subcommands triggers
PLUGIN_NAME = scheduler

include ../../common.mk
