SUBCOMMANDS = subcommands/report subcommands/set
TRIGGERS = triggers/backup-app-export triggers/backup-app-import triggers/backup-global-export triggers/backup-global-import triggers/scheduler-detect triggers/install triggers/post-app-clone-setup triggers/post-app-rename-setup triggers/post-delete triggers/report
BUILD = commands subcommands triggers
PLUGIN_NAME = scheduler

include ../../common.mk
