#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/git/functions"
source "$PLUGIN_AVAILABLE_PATH/git/internal-functions"
source "$PLUGIN_AVAILABLE_PATH/git/help-functions"

case "$1" in
  git-hook)
    cmd-git-hook "$@"
    ;;

  git-upload-pack)
    cmd-git-upload-pack "$@"
    ;;

  git-*)
    cmd-git-glob "$@"
    ;;

  help | git:help)
    cmd-git-help "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
