#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-git-deploy-source() {
  declare desc="git deploy-source plugin trigger"
  declare trigger="deploy-source"
  declare APP="$1"
  local STDIN
  STDIN=$(cat)

  # bail if another source is detected
  if [[ -n "$STDIN" ]]; then
    echo "$STDIN"
    return
  fi

  if [[ -d "$DOKKU_ROOT/$APP/refs" ]]; then
    echo "git"
  fi
}

trigger-git-deploy-source "$@"
