#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-git-post-delete() {
  declare desc="destroys the git properties for a given app"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "git" "$APP"
  "$PLUGIN_CORE_AVAILABLE_PATH/common/common" --quiet migrate-data-directory "git" "$APP"
}

trigger-git-post-delete "$@"
