#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

trigger-git-post-app-rename-setup() {
  declare desc="modifies git-hook"
  declare trigger="post-app-rename-setup"
  declare OLD_APP="$1" NEW_APP="$2"

  if [[ -f "$DOKKU_ROOT/$NEW_APP/hooks/pre-receive" ]]; then
    sed -i -e "s/git-hook $OLD_APP/git-hook $NEW_APP/g" "$DOKKU_ROOT/$NEW_APP/hooks/pre-receive"
  fi

  fn-plugin-property-clone "git" "$OLD_APP" "$NEW_APP"
  fn-plugin-property-destroy "git" "$OLD_APP" 
}

trigger-git-post-app-rename-setup "$@"
