#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/git/functions"

trigger-git-post-create() {
  declare desc="initializes an app with the correct git repository structure"
  declare trigger="post-create"
  declare APP="$1"

  fn-git-create-hook "$APP"
}

trigger-git-post-create "$@"
