#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/git/functions"

git_receive_app() {
  declare desc="git receive-app plugin trigger"
  local trigger="git_receive_app"
  local APP="$1"; local REV="$2"
  local cmd="git-build"

  # Don't trigger git build if there is no git repository.
  if [[ ! -d "$DOKKU_ROOT/$APP/refs" ]]; then
    true
  else
    # shellcheck disable=SC2086
    git_build_cmd $cmd $APP $REV
  fi
}

git_receive_app "$@"
