#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

ADDONS_PATH=/var/lib/dokku/addons

function die
{
  echo $* >&2
  exit 1
}

function check_app
{
  if [[ -z $1 ]]; then
    die "You must specify an app name"
  else
    APP="$1"
    ADDONS_FILE="$DOKKU_ROOT/$APP/ADDONS"
    ENV_FILE="$DOKKU_ROOT/$APP/ENV"

    # Check if app exists with the same name
    if [ ! -d "$DOKKU_ROOT/$APP" ]; then
      die "App $APP does not exist"
    fi

    [ -f $ADDONS_FILE ] || {
      echo "-----> Creating $ADDONS_FILE"
      touch $ADDONS_FILE
    }
    [ -f $ENV_FILE ] || {
      echo "-----> Creating $ENV_FILE"
      touch $ENV_FILE
    }
  fi
}

function check_addon
{
  if [[ -z $1 ]]; then
    die "You must specify an addon name"
  elif [ ! -d "$ADDONS_PATH/$ADDON" ]; then
    die "Addon $ADDON does not exist"
  fi
  ADDON=$1
  export ADDON_ROOT=$DOKKU_ROOT/.addons/$ADDON

  mkdir -p $ADDON_ROOT
}


#
# Each line of the ADDONS file is the form "name;id;private"
#
# The combination of the id and the private data is used by the addon to generate the url
#

case "$1" in
  addons)
    check_app $2
    cut -d";" -f1 $ADDONS_FILE
    ;;
  addons:add)
    check_app $2
    check_addon $3

    if cut -d";" -f1 $ADDONS_FILE | grep -q "^$ADDON$"; then
      die "App $APP already has addon $ADDON"
    fi

    id_private=$($ADDONS_PATH/$ADDON/provision $APP)

    echo "$ADDON;$id_private" >> $ADDONS_FILE

    ;;

  addons:remove)
    check_app $2
    check_addon $3

    line=$(grep "^$ADDON;" $ADDONS_FILE) || {
      die "App $APP does not have addon $ADDON"
    }

    id=$(cut -d";" -f2 <<< "$line")
    key=DOKKU_${ADDON^^}_URL

    $ADDONS_PATH/$ADDON/unprovision $id
    sed -i "/^$ADDON;/d" $ADDONS_FILE
    sed "/^export $key=/d" $ENV_FILE | sort > $ENV_FILE

    ;;

  addons:url)
    check_app $2
    check_addon $3

    line=$(grep "^$ADDON;" $ADDONS_FILE) || {
      die "App $APP does not have addon $ADDON"
    }

    id=$(cut -d";" -f2 <<< "$line")
    private=$(cut -d";" -f3 <<< "$line")

    $ADDONS_PATH/$ADDON/url $id $private

    ;;

  help)
    cat && cat<<EOF
    addons <app>                                    List add-ons enabled for an application
    addons:add <app> <addon>                        Add an add-on to an application
    addons:remove <app> <addon>                     Remove an add-on from an application (WARNING: may cause data loss)
    addons:url <app> <addon>                        Print the url export by an add-on
EOF

    ;;
esac

