#!/usr/bin/env bash
set -e

test_url() {
  path="$1"
  expected_output="$2"
  url="$base_url$path"
  output="$(curl -s -S "$url")"
  echo "$output"
  test "$output" == "$expected_output"
}

base_url="$1"
test_url / "python/http.server"
test_url /conftest "config-test"
test_url /hello "Hello
 'world'"
