#!/usr/bin/env bash
set -ex;

# shellcheck disable=SC2034
REMOTE=$1
REPO=$2

# setting config variables with spaces is broken at the moment. ref: 820
# ssh "$REMOTE" config:set "$REPO" CONFTEST=config-test HELLO=\"Hello world\"
dokku config:set "$REPO" CONFTEST=config-test HELLO="Hello world"
