#!/usr/bin/env bash
set -ex

REMOTE=$1
REPO=$2

GREETING=$(printf "Hello
 'world'" | base64)
ssh "$REMOTE" config:set "$REPO" CONFTEST=config-test
ssh "$REMOTE" config:set --encoded "$REPO" HELLO="$GREETING"
