#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/common/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-nixpacks-backup-app-import() {
  declare desc="restores the app's builder-nixpacks properties from the backup scope dir"
  declare trigger="backup-app-import"
  declare APP="$1" SCOPE_DIR="$2"
  "$PLUGIN_AVAILABLE_PATH/backup/backup-property" import "builder-nixpacks" "$APP" "$SCOPE_DIR"
}

trigger-builder-nixpacks-backup-app-import "$@"
