#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/config/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-nixpacks-builder-detect() {
  declare desc="builder-nixpacks builder-detect plugin trigger"
  declare trigger="builder-detect"
  declare APP="$1" SOURCECODE_WORK_DIR="$2"

  if [[ -f "$SOURCECODE_WORK_DIR/nixpacks.toml" ]]; then
    echo "nixpacks"
    return
  fi
}

trigger-builder-nixpacks-builder-detect "$@"
