#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-nixpacks-install() {
  declare desc="installs the builder-nixpacks plugin"
  declare trigger="install"

  fn-plugin-property-setup "builder-nixpacks"

  mkdir -p "${DOKKU_LIB_ROOT}/data/builder-nixpacks"
  chown -R "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "${DOKKU_LIB_ROOT}/data/builder-nixpacks"
}

trigger-builder-nixpacks-install "$@"
