#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/apps/functions"

apps_create_cmd() {
  declare desc="creates app via command line"
  local cmd="apps:create"
  apps_create "$2"
}

apps_create_cmd "$@"
