#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/apps/functions"

cmd-apps-exist() {
  declare desc="checks if an app exists"
  declare cmd="apps:exists"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  if ! apps_exists "$APP"; then
    dokku_log_fail "App does not exist"
  fi
  dokku_log_info1 "App exists"
}

cmd-apps-exist "$@"
