#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/apps/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

cmd-apps-rename() {
  declare desc="renames an app"
  declare cmd="apps:rename"
  [[ "$1" == "$cmd" ]] && shift 1
  declare OLD_APP="$1" NEW_APP="$2"

  [[ -z "$OLD_APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  [[ -d "$DOKKU_ROOT/$NEW_APP" ]] && dokku_log_fail "Name is already taken"

  apps_create "$NEW_APP"
  plugn trigger post-app-rename-setup "$OLD_APP" "$NEW_APP"
  DOKKU_APPS_FORCE_DELETE=1 apps_destroy "$OLD_APP"
  plugn trigger post-app-rename "$OLD_APP" "$NEW_APP"
  echo "Renaming $OLD_APP to $NEW_APP... done"
}

cmd-apps-rename "$@"
