#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

shopt -s nullglob
VERSION="$1"
IMPORT_DIR="$2"
TARGET_DIR="$3"

cd $IMPORT_DIR
for file in */VHOST; do
  cp $file "$TARGET_DIR/$file"
done
for file in */nginx.conf.template; do
  cp $file "$TARGET_DIR/$file"
done
