#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/domains/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-domains-domains-disable() {
  declare desc="disables domains for an app"
  declare trigger="domains-disable"
  declare APP="$1" RESTART_APP="$2"

  if [[ "$RESTART_APP" == "true" ]]; then
    disable_app_vhost "$APP"
  else
    disable_app_vhost "$APP" --no-restart
  fi
}

trigger-domains-domains-disable "$@"
