#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

get_app_domains() {
  local APP=$1; local VHOST_FILE="$DOKKU_ROOT/$APP/VHOST"
  verify_app_name $APP
  if [[ -f "$VHOST_FILE" ]]; then
    cat "$VHOST_FILE"
  fi
}
