#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-domains-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="domains"
  local plugin_description="Manage domains used by the proxy"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    domains:add <app> <domain> [<domain> ...], Add domains to app
    domains:add-global <domain> [<domain> ...], Add global domain names
    domains:clear <app>, Clear all domains for app
    domains:clear-global, Clear global domain names
    domains:disable <app>, Disable VHOST support
    domains:enable <app>, Enable VHOST support
    domains:remove <app> <domain> [<domain> ...], Remove domains from app
    domains:remove-global <domain> [<domain> ...], Remove global domain names
    domains:report [<app>|--global] [<flag>], Displays a domains report for one or more apps
    domains:set <app> <domain> [<domain> ...], Set domains for app
    domains:set-global <domain> [<domain> ...], Set global domain names
help_content
}
