#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/domains/functions"

trigger-domains-install() {
  declare desc="domains install trigger"
  declare trigger="install"

  shopt -s nullglob
  for app in $(dokku_apps); do
    domains_setup "$app"
  done
}

trigger-domains-install "$@"
