#!/usr/bin/env bash
[[ " help tags:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | tags:help)
    cat<<EOF
    tags <app>, List all app image tags
    tags:create <app> <tag>, Add tag to latest running app image
    tags:deploy <app> <tag>, Deploy tagged app image
    tags:destroy <app> <tag>, Remove app image tag
EOF
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
