#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

tag_image() {
  declare desc="convenience method for docker tag interface"
  docker tag -f "$1" "$2"
}
