#!/usr/bin/env bash
set -eo pipefail

echo "=====> resolve dokku.me"
sudo apt -qq -y --no-install-recommends install net-tools
# dokku.me now resolves to 10.0.0.2. add 10.0.0.2/24 to eth0
ifconfig
sudo ip addr add 10.0.0.2/24 broadcast 10.0.0.255 dev eth0

echo "=====> install ci-dependencies"
make ci-dependencies

echo "=====> setup tests"
./tests/ci/setup.sh

echo "=====> dokku cleanup:skip"
echo 'export DOKKU_SKIP_CLEANUP=true' | sudo tee /home/dokku/.dokkurc/dokku_skip_cleanup

echo "=====> dokku report"
dokku --trace report || {
  code="$?"
  echo "=====> bashenv files"
  sudo ls -lah /tmp/*bashenv*

  first=$(ls -t /tmp/*bashenv* | head -n 1)
  echo "=====> bashenv $first file contents"
  sudo cat "$first"
  exit $code
}
