#!/usr/bin/env bash
set -eo pipefail
set -x

echo "=====> set hostname"
hostname
internal_ip="$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')"
sudo hostname "dokku.me"
echo "dokku.me" | sudo tee /etc/hostname
hostname
sudo cat /etc/hostname

echo "=====> resolve dokku.me"
sudo apt -qq -y --no-install-recommends install net-tools
# dokku.me now resolves to 10.0.0.2. add 10.0.0.2/24 to eth0
ifconfig
sudo ip addr add 10.0.0.2/24 broadcast 10.0.0.255 dev eth0

echo "=====> install ci-dependencies"
make ci-dependencies

echo "=====> setup tests"
./tests/ci/setup.sh

echo "=====> dokku cleanup:skip"
echo 'export DOKKU_SKIP_CLEANUP=true' | sudo tee /home/dokku/.dokkurc/dokku_skip_cleanup

echo "=====> dokku report"
dokku report
