#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
case "$1" in
  plugins-install)
    pluginhook install
    exit $?
    ;;

  plugins-install-dependencies)
    pluginhook dependencies
    exit $?
    ;;

  plugins-update)
    pluginhook update
    exit $?
    ;;
esac

if [ -z $DOKKU_NO_COMMAND ]; then
  case "$1" in
    nginx:*)
      PLUGIN_NAME="nginx-vhosts"
      ;;
    *)
      PLUGIN_NAME="$1"
      ;;
  esac
  if [ -x $PLUGIN_PATH/$PLUGIN_NAME/command ]; then
    "$PLUGIN_PATH/$PLUGIN_NAME/command" "$@"
  elif [ -x $PLUGIN_PATH/${PLUGIN_NAME%%:*}/subcommands/${1#*:} ]; then
    "$PLUGIN_PATH/${PLUGIN_NAME%%:*}/subcommands/${1#*:}" "$@"
  else
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
  fi
fi
