#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"

docker_options_add_cmd() {
  declare desc="Add a docker option to application"
  local cmd="docker-options:add"

  verify_app_name "$2" && local APP="$2"
  read -ra passed_phases <<<"$(get_phases "$3")"
  shift 3 # everything else passed is the docker option
  local passed_docker_option="$*"
  [[ -z "$passed_docker_option" ]] && dokku_log_fail "Please specify docker options to add to the phase"
  add_passed_docker_option passed_phases[@] "${passed_docker_option[@]}"
}

docker_options_add_cmd "$@"
