#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"

cmd-docker-options-default() {
  declare desc="Display applications docker options"
  local cmd="docker-options"
  dokku_log_warn "Deprecated: Please use docker-options:report"

  verify_app_name "$2" && local APP="$2"
  read -ra passed_phases <<<"$(get_phases "$3")"
  if [[ ! "${passed_phases[@]}" ]]; then
    display_all_phases_options
  else
    display_passed_phases_options passed_phases[@]
  fi
}

cmd-docker-options-default "$@"
