#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"

docker_options_remove_cmd() {
  declare desc="Remove a docker option from application"
  local cmd="docker-options:remove"

  verify_app_name "$2" && local APP="$2"
  read -ra passed_phases <<<"$(get_phases "$3")"
  shift 3 # everything else passed is the docker option
  # shellcheck disable=SC2154
  [[ -z ${passed_docker_option="$@"} ]] && dokku_log_fail "Please specify docker options to remove from the phase"
  remove_passed_docker_option passed_phases[@] "${passed_docker_option[@]}"
}

docker_options_remove_cmd "$@"
