#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [ "$1" == "help" ]; then
    cat && cat<<EOF
    delete <app>                                    Delete an application
    run <app> <cmd>                                 Run a command in the environment of an application
    logs <app> [-t]                                 Show the last logs for an application (-t follows)
    url <app>                                       Show the URL for an application
EOF
fi
