#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/certs/functions"

certs_main_cmd() {
  declare desc="return certs plugin help content"
  local cmd="certs"
  help_formatted
}

certs_main_cmd "$@"

