#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/certs/functions"

certs_main_cmd() {
  declare desc="an alias for certs:info"
  local cmd="certs"
  certs_info_cmd "$@"
}

certs_main_cmd "$@"
