#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/certs/internal-functions"

cmd-certs-remove() {
  declare desc="removes SSL cert/key from specified app"
  declare cmd="certs:remove"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  verify_app_name "$APP"
  fn-certs-remove "$APP"
}

cmd-certs-remove "$@"
