#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-certs-remove() {
  declare desc="removes SSL cert/key from specified app"
  local cmd="certs:remove"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$2"
  local APP="$2"
  local APP_SSL_PATH="$DOKKU_ROOT/$APP/tls"

  if [[ -d "$APP_SSL_PATH" ]]; then
    dokku_log_info1 "Removing SSL endpoint from $APP"
    rm -rf "$APP_SSL_PATH"
    plugn trigger post-certs-remove "$APP"
    plugn trigger post-domains-update "$APP"
  else
    dokku_log_fail "An app-specific SSL endpoint is not defined"
  fi
}

cmd-certs-remove "$@"
