#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/command-functions"
source "$PLUGIN_AVAILABLE_PATH/haproxy-vhosts/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-haproxy-label-add() {
  declare desc="adds container label to app for specified proxy"
  declare cmd="haproxy:label:add"
  [[ "$1" == "$cmd" ]] && shift 1

  cmd-proxy-label-add "proxy:label:add" "haproxy" "$@"
}

cmd-haproxy-label-remove() {
  declare desc="removes container label from app for specified proxy"
  declare cmd="haproxy:label:remove"
  [[ "$1" == "$cmd" ]] && shift 1

  cmd-proxy-label-remove "proxy:label:remove" "haproxy" "$@"
}

cmd-haproxy-label-show() {
  declare desc="shows container labels for app for specified proxy"
  declare cmd="haproxy:label:show"
  [[ "$1" == "$cmd" ]] && shift 1

  cmd-proxy-label-show "proxy:label:show" "haproxy" "$@"
}

cmd-haproxy-report() {
  declare desc="displays a haproxy report for one or more apps"
  declare cmd="haproxy:report"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1" INFO_FLAG="$2"

  if [[ -n "$APP" ]] && [[ "$APP" == --* ]]; then
    INFO_FLAG="$APP"
    APP=""
  fi

  if [[ -z "$APP" ]] && [[ -z "$INFO_FLAG" ]]; then
    INFO_FLAG="true"
  fi

  if [[ -z "$APP" ]]; then
    for app in $(dokku_apps); do
      cmd-haproxy-report-single "$app" "$INFO_FLAG" | tee || true
    done
  else
    cmd-haproxy-report-single "$APP" "$INFO_FLAG"
  fi
}

cmd-haproxy-report-single() {
  declare APP="$1" INFO_FLAG="$2"
  if [[ "$INFO_FLAG" == "true" ]]; then
    INFO_FLAG=""
  fi
  verify_app_name "$APP"
  local flag_map=(
    "--haproxy-image: $(fn-haproxy-image)"
    "--haproxy-letsencrypt-email: $(fn-haproxy-letsencrypt-email)"
    "--haproxy-letsencrypt-server: $(fn-haproxy-letsencrypt-server)"
    "--haproxy-log-level: $(fn-haproxy-log-level)"
  )

  if [[ -z "$INFO_FLAG" ]]; then
    dokku_log_info2_quiet "${APP} haproxy information"
    for flag in "${flag_map[@]}"; do
      key="$(echo "${flag#--}" | cut -f1 -d' ' | tr - ' ')"
      dokku_log_verbose "$(printf "%-30s %-25s" "${key^}" "${flag#*: }")"
    done
  else
    local match=false
    local value_exists=false
    for flag in "${flag_map[@]}"; do
      valid_flags="${valid_flags} $(echo "$flag" | cut -d':' -f1)"
      if [[ "$flag" == "${INFO_FLAG}:"* ]]; then
        value=${flag#*: }
        size="${#value}"
        if [[ "$size" -ne 0 ]]; then
          echo "$value" && match=true && value_exists=true
        else
          match=true
        fi
      fi
    done
    [[ "$match" == "true" ]] || dokku_log_fail "Invalid flag passed, valid flags:${valid_flags}"
  fi
}

cmd-haproxy-logs() {
  declare desc="display haproxy logs from command line"
  declare cmd="haproxy:logs"
  [[ "$1" == "$cmd" ]] && shift 1
  local NUM="100" TAIL=false

  local TEMP=$(getopt -o htn: --long help,tail,num: -n 'dokku haproxy:logs' -- "$@")
  local EXIT_CODE="$?"
  if [[ "$EXIT_CODE" != 0 ]]; then
    fn-haproxy-logs-usage >&2
    exit 1
  fi
  eval set -- "$TEMP"

  while true; do
    case "$1" in
      -t | --tail)
        local TAIL=true
        shift
        ;;
      -n | --num)
        local NUM="$2"
        shift 2
        ;;
      --)
        shift
        break
        ;;
      *) dokku_log_fail "Internal error" ;;
    esac
  done

  fn-haproxy-logs "$TAIL" "$NUM"
}

cmd-haproxy-show-config() {
  declare desc="display haproxy config"
  declare cmd="haproxy:show-config"
  [[ "$1" == "$cmd" ]] && shift 1

  if ! fn-is-compose-installed; then
    dokku_log_fail "Required docker compose plugin is not installed"
  fi

  local TMP_COMPOSE_FILE=$(mktemp "/tmp/dokku-${DOKKU_PID}-${FUNCNAME[0]}.XXXXXX")
  trap "rm -rf '$TMP_COMPOSE_FILE' >/dev/null" RETURN INT TERM EXIT

  fn-haproxy-template-compose-file "$TMP_COMPOSE_FILE"
  cat "$TMP_COMPOSE_FILE"
}

cmd-haproxy-start() {
  declare desc="Starts the haproxy server"
  declare cmd="haproxy:start"
  [[ "$1" == "$cmd" ]] && shift 1

  if ! fn-is-compose-installed; then
    dokku_log_fail "Required docker compose plugin is not installed"
  fi

  local TMP_COMPOSE_FILE=$(mktemp "/tmp/dokku-${DOKKU_PID}-${FUNCNAME[0]}.XXXXXX")
  trap "rm -rf '$TMP_COMPOSE_FILE' >/dev/null" RETURN INT TERM EXIT

  fn-plugin-property-write "haproxy" "--global" "proxy-status" "started"
  fn-haproxy-template-compose-file "$TMP_COMPOSE_FILE"
  if ! "$PLUGIN_CORE_AVAILABLE_PATH/common/common" compose-up "haproxy" "$TMP_COMPOSE_FILE"; then
    return 1
  fi
}

cmd-haproxy-stop() {
  declare desc="Stops the haproxy server"
  declare cmd="haproxy:stop"
  [[ "$1" == "$cmd" ]] && shift 1

  if ! fn-is-compose-installed; then
    dokku_log_fail "Required docker compose plugin is not installed"
  fi

  local TMP_COMPOSE_FILE=$(mktemp "/tmp/dokku-${DOKKU_PID}-${FUNCNAME[0]}.XXXXXX")
  trap "rm -rf '$TMP_COMPOSE_FILE' >/dev/null" RETURN INT TERM EXIT

  fn-plugin-property-write "haproxy" "--global" "proxy-status" "stopped"
  fn-haproxy-template-compose-file "$TMP_COMPOSE_FILE"
  if ! "$PLUGIN_CORE_AVAILABLE_PATH/common/common" compose-down "haproxy" "$TMP_COMPOSE_FILE"; then
    return 1
  fi
}
