#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-haproxy-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="haproxy"
  local plugin_description="Manage the haproxy proxy integration"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    haproxy:report [<app>] [<flag>], Displays an haproxy report for one or more apps
    haproxy:set <app> <property> (<value>), Set or clear an haproxy property for an app
    haproxy:show-config <app>, Display haproxy compose config
    haproxy:start, Starts the haproxy server
    haproxy:stop, Stops the haproxy server
help_content
}
