#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-haproxy-install() {
  declare desc="installs the haproxy plugin"
  declare trigger="install"

  mkdir -p "${DOKKU_LIB_ROOT}/data/haproxy"
  chown -R "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "${DOKKU_LIB_ROOT}/data/haproxy"

  fn-plugin-property-setup "haproxy"
}

trigger-caddy-install "$@"
