#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-haproxy-vhosts-post-delete() {
  declare desc="haproxy-vhosts post-delete trigger"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "haproxy" "$APP"
}

trigger-haproxy-vhosts-post-delete "$@"
