#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

tar_from_cmd() {
  local desc="deploys app from tarball at URL via command line"
  local cmd="tar:from"
  verify_app_name "$2"
  local APP=$2
  local URL=$3
  shift 3
  curl -# --insecure -L "$URL" | dokku tar:in "$APP" "$@"
}

tar_from_cmd "$@"
