#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

tar_in_cmd() {
  declare desc="deploys app from tarball on STDIN via command line"
  local cmd="tar:in"
  local APP="$2"

  verify_app_name "$2"
  tee "$DOKKU_ROOT/$APP/src.tar" | wc -c
  plugn trigger receive-app "$APP"
}

tar_in_cmd "$@"
