#!/usr/bin/env bash
# help:<app>:Show the URL for an application
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ -z $1 ]]; then
	echo "Please specify an app"
	exit 1
fi
APP="$1";
	if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
		echo "App $APP does not exist"
	exit 1
fi

if [[ -f "$DOKKU_ROOT/$APP/URL" ]]; then
	echo $(< "$DOKKU_ROOT/$APP/URL")
fi

