#!/usr/bin/env bash
[[ " help checks:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | ps:help)
    cat<<EOF
    checks <app>, Show zero-downtime status
    checks:enable <app>, Enable zero-downtime checks
    checks:disable <app>, Disable zero-downtime checks
EOF
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
