#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

is_app_proctype_checks_disabled() {
  declare desc="return true if app's proctype(s) checks are disabled"
  local APP="$1"
  local PROCTYPE="$2" status=false
  local DOKKU_CHECKS_DISABLED=$(fn-plugin-property-get-default "checks" "$APP" "disabled" "")

  if [[ "$DOKKU_CHECKS_DISABLED" == "_all_" ]] || [[ "$(is_val_in_list "$PROCTYPE" "$DOKKU_CHECKS_DISABLED")" == "true" ]]; then
    status=true
  fi

  echo $status
}

is_app_proctype_checks_skipped() {
  declare desc="return true if app's proctype(s) checks are skipped"
  local APP="$1"
  local PROCTYPE="$2" status=false
  local DOKKU_CHECKS_SKIPPED=$(fn-plugin-property-get-default "checks" "$APP" "skipped" "")

  if [[ "$DOKKU_CHECKS_SKIPPED" == "_all_" ]] || [[ "$(is_val_in_list "$PROCTYPE" "$DOKKU_CHECKS_SKIPPED")" == "true" ]]; then
    status=true
  fi

  echo $status
}
