#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

main() {
  declare desc="determines the build type for an application"
  declare APP="$1" BUILD_TYPE="2" TMP_WORK_DIR="$3"
  declare STDIN
  STDIN=$(cat)

  if [[ -n "$BUILD_TYPE" ]]; then
    echo "$STDIN"
    return
  fi

  pushd "$TMP_WORK_DIR" > /dev/null
  if [[ -f Dockerfile ]] && [[ "$([[ -f .env ]] && grep -q BUILDPACK_URL .env; echo $?)" != "0" ]] && [[ ! -f ".buildpacks" ]] && [[ -z $(config_get "$APP" BUILDPACK_URL || true) ]]; then
    echo "dockerfile"
    return
  fi

  echo "$STDIN"
}

main "$@"
