#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-dockerfile-builder-release() {
  declare desc="builder-dockerfile builder-release plugin trigger"
  declare trigger="builder-release"
  declare BUILDER_TYPE="$1" APP="$2" IMAGE_TAG="$3"

  if [[ "$BUILDER_TYPE" != "dockerfile" ]]; then
    return
  fi

  # buildstep plugins don't necessarily make sense for dockerfiles. call the new breed!!!
  plugn trigger pre-release-dockerfile "$APP" "$IMAGE_TAG"
  plugn trigger post-release-dockerfile "$APP" "$IMAGE_TAG"
}

trigger-builder-dockerfile-builder-release "$@"
