#!/usr/bin/env bash
[[ " help proxy:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | proxy:help)
    cat<<EOF
    proxy <app>, Show proxy for app
    proxy:enable <app>, Enable proxy for app
    proxy:disable <app>, Disable proxy for app
    proxy:set <app> <proxy_type>, NOT IMPLEMENTED YET!!
EOF
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
