#!/usr/bin/env bash
[[ " help proxy:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | proxy:help)
    help_content_func () {
      declare desc="return proxy plugin help content"
      cat<<help_content
    proxy <app>, Show proxy settings for app
    proxy:enable <app>, Enable proxy for app
    proxy:disable <app>, Disable proxy for app
    proxy:ports <app>, List proxy port mappings for app
    proxy:ports-clear <app>, Clear all proxy port mappings for app
    proxy:ports-add <app> <scheme>:<host-port>:<container-port> [<scheme>:<host-port>:<container-port>...], Set proxy port mappings for app
    proxy:ports-remove <app> <host-port> [<host-port>...], Unset proxy port mappings for app
    proxy:set <app> <proxy-type>, Set proxy type for app
help_content
    }

    if [[ $1 = "proxy:help" ]] ; then
        echo -e 'Usage: dokku proxy[:COMMAND]'
        echo ''
        echo 'Control the proxy used by dokku, per app.'
        echo ''
        echo 'Additional commands:'
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
