#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

is_app_proxy_enabled() {
  declare desc="return true if proxy is enabled; otherwise return false"
  declare APP="$1"
  declare deprecated=true
  dokku_log_warn "Deprecated: plugn#proxy-is-enabled"

  plugn trigger proxy-is-enabled "$APP"
}

get_app_proxy_type() {
  declare desc="return app proxy type"
  declare APP="$1"
  declare deprecated=true
  dokku_log_warn "Deprecated: plugn#proxy-type"

  plugn trigger proxy-type "$APP"
}
