#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

trigger-proxy-post-certs-remove() {
  declare desc="unset port config vars after SSL cert is removed"
  local trigger="nginx_post_certs_remove"
  local APP="$1"

  config_unset --no-restart "$APP" DOKKU_PROXY_SSL_PORT

  # shellcheck disable=SC2046
  remove_proxy_ports "$APP" $(filter_app_proxy_ports "$APP" "https" "443")
}

trigger-proxy-post-certs-remove "$@"
