TRIGGERS = triggers/backup-app-export triggers/backup-app-import triggers/backup-global-export triggers/backup-global-import triggers/scheduler-cron-write triggers/scheduler-storage-exec
BUILD = triggers
PLUGIN_NAME = scheduler-docker-local

include ../../common.mk
