#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-scheduler-docker-local-post-create() {
  declare desc="scheduler-docker-local post-create plugin trigger"
  declare trigger="post-create"
  declare APP="$1"

  "$PLUGIN_CORE_AVAILABLE_PATH/common/common" --quiet create-data-directory "scheduler-docker-local" "$APP"
}

trigger-scheduler-docker-local-post-create "$@"
