#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

scheduler-docker-local-scheduler-stop() {
  declare desc="scheduler-docker-local scheduler-stop plugin trigger"
  declare trigger="scheduler-docker-local scheduler-stop"
  declare DOKKU_SCHEDULER="$1" APP="$2" REMOVE_CONTAINERS="$3"

  if [[ "$DOKKU_SCHEDULER" != "docker-local" ]]; then
    return
  fi

  local DOKKU_APP_RUNNING_CONTAINER_IDS=$(get_app_running_container_ids "$APP")
  local DOKKU_DOCKER_STOP_TIMEOUT="$(config_get "$APP" DOKKU_DOCKER_STOP_TIMEOUT || true)"

  [[ -n "$DOKKU_DOCKER_STOP_TIMEOUT" ]] && DOCKER_STOP_TIME_ARG="--time=${DOKKU_DOCKER_STOP_TIMEOUT}"

  if [[ -n "$DOKKU_APP_RUNNING_CONTAINER_IDS" ]]; then
    # shellcheck disable=SC2086
    docker stop $DOCKER_STOP_TIME_ARG $DOKKU_APP_RUNNING_CONTAINER_IDS > /dev/null || true
  fi

  if [[ "$REMOVE_CONTAINERS" == "true" ]]; then
    local DOKKU_APP_CIDS=$(get_app_container_ids "$APP")

    if [[ -n "$DOKKU_APP_CIDS" ]]; then
      # shellcheck disable=SC2086
      docker rm -f $DOKKU_APP_CIDS > /dev/null 2>&1 || true
    fi
  fi
}


scheduler-docker-local-scheduler-stop "$@"
