#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/scheduler/functions"

trigger-scheduler-container-cleanup() {
  declare desc="cleans up all exited/dead containers and removes all dangling images"
  local SCHEDULER_NAME

  if fn-scheduler-should-use "docker-local"; then
    return
  fi

  # delete all non-running containers
  # shellcheck disable=SC2046
  docker rm $(docker ps -a -f "status=exited" -f "label=$DOKKU_CONTAINER_LABEL" -q) &> /dev/null || true

  # delete all dead containers
  # shellcheck disable=SC2046
  docker rm $(docker ps -a -f "status=dead" -f "label=$DOKKU_CONTAINER_LABEL" -q) &> /dev/null || true

  # delete unused images
  # shellcheck disable=SC2046
  docker rmi $(docker images -f 'dangling=true' -q) &> /dev/null &
}

trigger-scheduler-container-cleanup "$@"
