#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/scheduler/functions"

trigger-container-image-tag() {
  declare desc="retrieve current image tag for a given app. returns empty string if no deployed containers are found"
  local SCHEDULER_NAME

  if fn-scheduler-should-use "docker-local"; then
    return
  fi

  local APP="$1"
  [[ ! -n "$APP" ]] && dokku_log_fail "(get_running_image_tag) APP must not be null"
  verify_app_name "$APP"

  local CIDS=( $(get_app_container_ids "$APP") )
  local RUNNING_IMAGE_TAG=$(docker inspect -f '{{ .Config.Image }}' "${CIDS[0]}" 2>/dev/null | awk -F: '{ print $2 }' || echo '')
  echo "$RUNNING_IMAGE_TAG"
}

trigger-container-image-tag "$@"
