#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/scheduler/functions"

trigger-scheduler-image-copy() {
  declare desc="copy file from named image to destination"
  local SCHEDULER_NAME

  if fn-scheduler-should-use "docker-local"; then
    return
  fi

  local IMAGE="$1"; local SRC_FILE="$2"; local DST_DIR="$3"
  verify_app_name "$APP"

  if ! verify_image "$IMAGE"; then
    exit 1
  fi

  if ! is_abs_path "$SRC_FILE"; then
    local WORKDIR=$(docker inspect -f '{{.Config.WorkingDir}}' "$IMAGE")
    [[ -z "$WORKDIR" ]] && local WORKDIR=/app
    local SRC_FILE="$WORKDIR/$SRC_FILE"
  fi
  local CID=$(docker run "$DOKKU_GLOBAL_RUN_ARGS" -d "$IMAGE" bash)
  docker cp "$CID:$SRC_FILE" "$DST_DIR"
  docker rm -f "$CID" &> /dev/null
}

trigger-scheduler-image-copy "$@"
