#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

scheduler-docker-local-scheduler-tags-destroy() {
  declare desc="scheduler-docker-local scheduler-stop plugin trigger"
  declare trigger="scheduler-docker-local scheduler-stop"
  declare DOKKU_SCHEDULER="$1" APP="$2" IMAGE_REPO="$3" IMAGE_TAG="$4"

  if [[ "$DOKKU_SCHEDULER" != "docker-local" ]]; then
    return
  fi

  docker rmi "$IMAGE_REPO:$IMAGE_TAG"
}

scheduler-docker-local-scheduler-tags-destroy "$@"
