#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/scheduler/functions"

trigger-scheduler-image-is-herokuish() {
  declare desc="returns true if app image is based on herokuish"
  local SCHEDULER_NAME

  if fn-scheduler-should-use "docker-local"; then
    return
  fi

  # circleci can't support --rm as they run lxc in lxc
  [[ ! -f "/home/ubuntu/.circlerc" ]] && local DOCKER_ARGS="--rm"
  docker run "$DOKKU_GLOBAL_RUN_ARGS" --entrypoint="/bin/sh" $DOCKER_ARGS "$@" -c "test -f /exec" &> /dev/null
}

trigger-scheduler-image-is-herokuish "$@"
