#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/ssh-keys/functions"

ssh_keys_main_cmd() {
  declare desc="return ssh-keys plugin help content"
  local cmd="ssh-keys"
  help_formatted
}

ssh_keys_main_cmd "$@"
