#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/ssh-keys/functions"

list_ssh_keys() {
  declare desc="List ssh key hashes"
  verify_ssh_key_file
  sshcommand list dokku
}

list_ssh_keys "$@"
