#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ssh-keys/functions"

remove_key() {
  declare desc="Removes key from authorized_keys"
  local cmd="ssh-keys:remove"
  shift
  local name="$1"
  verify_ssh_key_file
  [[ -z $1 ]] && dokku_log_fail "A name is required to remove a key, ie: dokku ssh-keys:remove <name>"
  sshcommand acl-remove dokku "$name" || dokku_log_fail "sshcommand returned an error $?"
}

remove_key "$@"
