#!/usr/bin/env bash
[[ " help plugin:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | plugin:help)
    cat<<EOF
    plugin, Print active plugins
    plugin:install [--core|git-url [--committish tag|branch|commit|--name custom-plugin-name]], Optionally download git-url (with custom tag/committish) & run install trigger for active plugins (or only core ones)
    plugin:install-dependencies [--core], Run install-dependencies trigger for active plugins (or only core ones)
    plugin:update [name [committish]], Optionally update named plugin from git (with custom tag/committish) & run update trigger for active plugins
    plugin:enable <name>, Enable a previously disabled plugin
    plugin:disable <name>, Disable an installed plugin (third-party only)
    plugin:uninstall <name>, Uninstall a plugin (third-party only)
EOF
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac


