#!/usr/bin/env bash
[[ " help plugin:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
source "$PLUGIN_AVAILABLE_PATH/plugin/help-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | plugin:help)
    cmd-plugin-help "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
