#!/usr/bin/env bash
set -eo pipefail

APP="$1"
IMAGE="$2"

# kill the app when running
if [[ -f "$DOKKU_ROOT/$APP/PORT" ]]; then
  oldid=$(< "$DOKKU_ROOT/$APP/CONTAINER")
  docker kill $oldid > /dev/null
fi

# start the app
id=$(docker run -d -p 5000 -e PORT=5000 $IMAGE /bin/bash -c "/start web")
echo $id > "$DOKKU_ROOT/$APP/CONTAINER"
port=$(docker port $id 5000 | sed 's/0.0.0.0://')
echo $port > "$DOKKU_ROOT/$APP/PORT"
echo "http://$(< "$DOKKU_ROOT/HOSTNAME"):$port" > "$DOKKU_ROOT/$APP/URL"
