#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

trace_off_cmd() {
  declare desc="disables trace mode"
  local cmd="trace"
  [[ -d $DOKKU_ROOT/.dokkurc ]] || mkdir -p "$DOKKU_ROOT/.dokkurc"

  dokku_log_info1 "Disabling trace mode"
  rm -f "$DOKKU_ROOT/.dokkurc/DOKKU_TRACE"
}

trace_off_cmd "$@"
