#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ -z $2 ]]; then
    echo "Please specify an app to delete"
    exit 1
fi
APP="$2"; IMAGE="dokku/$APP";
if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
    echo "App does not exist"
    exit 1
fi

pluginhook pre-delete $APP
if [[ -f "$DOKKU_ROOT/$APP/CONTAINER" ]]; then
  ID=$(< "$DOKKU_ROOT/$APP/CONTAINER")

  docker stop $ID > /dev/null || true
  docker rm $ID  > /dev/null || true
fi

docker images | grep $IMAGE | awk '{print $3}' | xargs docker rmi &> /dev/null &

pluginhook post-delete $APP
