#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

apps_create() {
  [[ -z $1 ]] && dokku_log_fail "Please specify an app to run the command on"
  [[ ! "$1" =~ ^[a-z].* && ! "$1" =~ ^[0-9].* ]] && dokku_log_fail "App name must begin with lowercase alphanumeric character"
  [[ -d "$DOKKU_ROOT/$1" ]] && dokku_log_fail "Name is already taken"
  local APP="$1"

  mkdir -p "$DOKKU_ROOT/$APP"
  echo "Creating $APP... done"
  plugn trigger post-create $APP
}
