#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

apps_pre_delete() {
  declare desc="apps pre-delete plugin trigger"
  local trigger="apps_pre_delete"
  local APP="$1"; local IMAGE_TAG="$2"; local IMAGE=$(get_deploying_app_image_name "$APP" "$IMAGE_TAG"); local CACHE_DIR="$DOKKU_ROOT/$APP/cache"; local CACHE_HOST_ROOT="$DOKKU_HOST_ROOT/$APP/cache"
  verify_app_name "$APP"

  if ! is_image_herokuish_based "$IMAGE"; then
    return
  fi

  if [[ -d $CACHE_DIR ]]; then
    docker run "$DOKKU_GLOBAL_RUN_ARGS" --rm -v "$CACHE_HOST_ROOT:/cache" "$IMAGE" find /cache -depth -mindepth 1 -maxdepth 1 -exec rm -Rf {} \; || true
  fi
}

apps_pre_delete "$@"
