#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

trigger-ps-app-restart() {
  declare desc="ps app-restart plugin trigger"
  declare trigger="app-restart"
  declare APP="$1"

  ps_restart "$APP"
}

trigger-ps-app-restart "$@"
