#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

trigger-ps-core-post-deploy() {
  declare desc="ps core-post-deploy plugin trigger"
  declare trigger="core-post-deploy"
  declare APP="$1"

  remove_procfile "$APP"
  DOKKU_QUIET_OUTPUT=1 config_set --no-restart "$APP" DOKKU_APP_RESTORE=1
}

trigger-ps-core-post-deploy "$@"
