#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

release_and_deploy() {
  local APP="$1"; local IMAGE="dokku/$APP"

  if [[ -f "$DOKKU_ROOT/$APP/CONTAINER" ]]; then
    if is_image_buildstep_based "$IMAGE"; then
      IMAGE_SOURCE_TYPE="buildstep"
    else
      IMAGE_SOURCE_TYPE="dockerfile"
    fi

    dokku_log_info1 "Releasing $APP ..."
    dokku release "$APP" "$IMAGE_SOURCE_TYPE"
    dokku_log_info1 "Deploying $APP ..."
    dokku deploy "$APP"
    dokku_log_info2 "Application deployed:"
         dokku urls $APP | sed "s/^/       /"
    echo
  fi
}
