#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

trigger-ps-install() {
  declare desc="set the default restart policy for all applications if there is not one already set"
  declare trigger="install"
  local APPS="$(dokku_apps)"
  local APP

  mkdir -p "${DOKKU_LIB_ROOT}/data/ps"
  chown -R "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "${DOKKU_LIB_ROOT}/data/ps"

  for APP in $APPS; do
    local RESTART_POLICIES=$(get_restart_policies "$(get_phase_file_path "deploy")")
    if [[ -z "$RESTART_POLICIES" ]]; then
      local passed_phases=(deploy)
      add_passed_docker_option passed_phases[@] "--restart=on-failure:10"
    fi
  done
}

trigger-ps-install "$@"
