#!/usr/bin/env bash
set -eo pipefail
APP="$1";
APP_PATH="$DOKKU_ROOT/$APP"

while read line; do
  NUM=${line#*=}
  for ((i=1; i<=$NUM; i++)); do
    PORT=$(docker port $APP.web.$i 5000 | sed 's/0.0.0.0://')
    if [[ -n "$PORT" ]]; then
      upstreams=${upstreams}"server 127.0.0.1:$PORT; "
    fi
  done

  if [[ -n "$upstreams" ]]; then
    upstream="upstream $APP {${upstreams}}"
    sed -i '1s/^upstream.*/'"$upstream"'/' "$APP_PATH/nginx.conf"
  fi
done <<< "$(grep "^web=" "$APP_PATH/PS")"