#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

ps_post_stop() {
  declare desc="ps post-stop plugin trigger"
  local trigger="ps_post_stop"
  local APP="$1"

  set_config_value "app.$APP" DOKKU_APP_RESTORE 0
}
