#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

ps_post_deploy() {
  local desc="ps post-deploy plugin trigger"
  local trigger="ps_post_deploy"
  local APP="$1"

  remove_procfile "$APP"
  config_set --no-restart "$APP" DOKKU_APP_RESTORE=1
}

ps_post_deploy "$@"
