#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

config_main_cmd() {
  local desc="print config vars for app via command line"
  local cmd="config"
  config_all "$@"
}

config_main_cmd "$@"
