#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/../functions"

ENV_FILE="$DOKKU_ROOT/$2/ENV"

[[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
verify_app_name "$2"
APP="$2"

if [[ -z $3 ]]; then
  echo "Usage: dokku config:get APP KEY"
  echo "Must specify KEY."
  exit 1
fi

config_create
if [[ ! -s $ENV_FILE ]] ; then
  exit 0
fi

KEY="$3"

grep -Eo "export ([a-zA-Z_][a-zA-Z0-9_]*=.*)" $ENV_FILE | grep "^export $KEY=" | cut -d"=" -f2- | sed -e "s/^'//" -e "s/'$//"
