#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

config_get_cmd() {
  local desc="get specified config vars from app via command line"
  local cmd="config:get"
  config_get "$@"
}

config_get_cmd "$@"
