#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ -z $3 ]]; then
  echo "Usage: dokku config:get APP KEY"
  echo "Must specify KEY."
  exit 1
fi

if [ ! -f $ENV_FILE ] || [ ! -s $ENV_FILE ] ; then
  exit 1
fi

KEY="$3"

cat $ENV_FILE | grep -Eo "export ([a-zA-Z_][a-zA-Z0-9_]*=.*)" | cut -d" " -f2 | grep "^$KEY=" | cut -d"=" -f2-
