#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/../functions"

ENV_FILE="$DOKKU_ROOT/$2/ENV"

[[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
verify_app_name "$2"
APP="$2"

if [[ -z "${*:3}" ]]; then
  echo "Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]"
  echo "Must specify KEY and VALUE to set."
  exit 1
fi

shift 2
dokku config:set-norestart $APP "$@"
dokku_log_info1 "Restarting app $APP"
dokku ps:restart $APP
