#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

config_set_cmd() {
  local desc="set specified config vars for app via command line"
  local cmd="config:set"
  config_set "$@"
}

config_set_cmd "$@"
