#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/../functions"

ENV_FILE="$DOKKU_ROOT/$2/ENV"

[[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
verify_app_name "$2"
APP="$2"

if [[ -z "${*:3}" ]]; then
  echo "Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]"
  echo "Must specify KEY and VALUE to set."
  exit 1
fi

config_create
ENV_ADD=""
ENV_TEMP=$(cat "${ENV_FILE}")
RESTART_APP=false
shift 2

for var; do
  if [[ $var != *"="* ]]; then
    echo "Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]"
    echo "Must specify KEY and VALUE to set."
    exit 1
  fi
done

for var; do
  KEY=$(echo ${var} | cut -d"=" -f1)
  VALUE=$(echo ${var} | cut -d"=" -f2-)

  if [[ $KEY =~ [a-zA-Z_][a-zA-Z0-9_]* ]]; then
    RESTART_APP=true
    ENV_TEMP=$(echo -e "${ENV_TEMP}" | sed "/^export $KEY=/ d")
    ENV_TEMP="${ENV_TEMP}\nexport $KEY='$VALUE'"
    ENV_ADD=$(echo -e "${ENV_ADD}" | sed "/^$KEY=/ d")
    ENV_ADD="${ENV_ADD}$
${var}"
  fi
done
ENV_ADD=$(echo "$ENV_ADD" | tail -n +2) #remove first empty line

if [ $RESTART_APP ]; then
  dokku_log_info1 "Setting config vars"
  config_styled_hash "$ENV_ADD" "       "

  config_write "$ENV_TEMP"
fi
