#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/../functions"

ENV_FILE="$DOKKU_ROOT/$2/ENV"

[[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
verify_app_name "$2"
APP="$2"

if [[ -z $3 ]]; then
  echo "Usage: dokku config:unset APP KEY1 [KEY2 ...]"
  echo "Must specify KEY to unset."
  exit 1
fi

shift 2
dokku config:unset-norestart $APP "$@"
dokku_log_info1 "Restarting app $APP"
dokku ps:restart $APP
