#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_NAME=${1%%:*}

dokku $PLUGIN_NAME:init $2

if [[ -z $3 ]]; then
  echo "Usage: dokku config:unset APP KEY1 [KEY2 ...]"
  echo "Must specify KEY to unset."
  exit 1
fi

APP="$2"; APP_DIR="$DOKKU_ROOT/$APP"
ENV_TEMP=`cat "${ENV_FILE}"`
VARS="${*:3}"

for var in $VARS; do
  echo "-----> Unsetting $var and restarting $APP"
  ENV_TEMP=$(echo -e "${ENV_TEMP}" | sed "/^export $var=/ d")

  echo -e "$ENV_TEMP" | sed '/^$/d' | sort > $ENV_FILE
  dokku $PLUGIN_NAME:restart "$APP"
done
