#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$2"; IMAGE="dokku/$APP"
pluginhook pre-deploy $APP

# kill the app when running
if [[ -f "$DOKKU_ROOT/$APP/CONTAINER" ]]; then
  oldid=$(< "$DOKKU_ROOT/$APP/CONTAINER")
  docker inspect $oldid &> /dev/null && docker kill $oldid > /dev/null
fi

# start the app
DOCKER_ARGS=$(: | pluginhook docker-args $APP)
id=$(docker run -d -p 5000 -e PORT=5000 $DOCKER_ARGS $IMAGE /bin/bash -c "/start web")
echo $id > "$DOKKU_ROOT/$APP/CONTAINER"
port=$(docker port $id 5000 | sed 's/0.0.0.0://')
echo $port > "$DOKKU_ROOT/$APP/PORT"
echo "http://$(< "$DOKKU_ROOT/HOSTNAME"):$port" > "$DOKKU_ROOT/$APP/URL"

pluginhook post-deploy $APP $port
