#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

plugin_main_cmd() {
  declare desc="shows details about locally installed plugins"
  local cmd="plugin"
  plugn version
  plugn list
}

plugin_main_cmd "$@"
