#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/plugin/functions"
source "$PLUGIN_AVAILABLE_PATH/plugin/internal-functions"

plugin_enable_cmd() {
  declare desc="enables plugin via command line"
  local cmd="plugin:enable"
  [[ -z $2 ]] && dokku_log_fail "Please specify a plugin to enable"
  local PLUGIN="$2"
  enable_plugin "$PLUGIN"
  plugin_prime_bash_completion
}

plugin_enable_cmd "$@"
