#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-plugin-install-dependencies() {
  declare desc="calls dependencies plugin trigger via command line"
  local cmd="plugin:install-dependencies"
  if [[ $2 == "--core" ]]; then
    export PLUGIN_PATH="$PLUGIN_CORE_PATH"
  fi
  plugn trigger dependencies
}

cmd-plugin-install-dependencies "$@"
