#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/plugin/internal-functions"

cmd-plugin-update() {
  declare desc="updates plugin to optional committish and calls update plugin trigger via command line"
  declare cmd="plugin:update"
  [[ "$1" == "$cmd" ]] && shift 1
  declare PLUGIN="$1" PLUGIN_COMMITTISH="$2"

  if [[ -n "$PLUGIN" ]]; then
    plugn update "$PLUGIN" "$PLUGIN_COMMITTISH"
  fi
  plugn trigger update
  plugin_prime_bash_completion
}

cmd-plugin-update "$@"
