#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/plugin/internal-functions"

cmd-plugin-update() {
  declare desc="updates plugin to optional committish and calls update plugin trigger via command line"
  local cmd="plugin:update"
  if [[ -n "$2" ]]; then
    local PLUGIN="$2"
    local PLUGIN_COMMITTISH="$3"
    plugn update "$PLUGIN" "$PLUGIN_COMMITTISH"
  fi
  plugn trigger update
  plugin_prime_bash_completion
}

cmd-plugin-update "$@"
