#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

fn-logs-usage() {
  declare desc="logs specific usage"
  echo "Usage: dokku logs <app>"
  echo " display recent log output"
  echo ""
  echo " -n, --num NUM        # the number of lines to display"
  echo " -p, --ps PS          # only display logs from the given process"
  echo " -t, --tail           # continually stream logs"
  echo " -q, --quiet          # display raw logs without colors, time and names"
}
