#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/tags/functions"

tags_deploy_cmd() {
  declare desc="deploys an app with a given tagged image via command line"
  local cmd="tags:deploy"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  local APP="$2"; local IMAGE_TAG="$3"
  verify_app_name "$APP"

  local IMAGE="$(get_app_image_name "$APP" "$IMAGE_TAG")"
  verify_image "$IMAGE" || return 1
  release_and_deploy "$APP" "$IMAGE_TAG"  
}

tags_deploy_cmd "$@"
