#!/bin/bash

apt-get install -y postgresql-client-common postgresql-client-9.1    # Postgres client
apt-get install -y postgresql                                        # Postgres server for local DB

mkdir -p /etc/dokku

cat<<EOF > /etc/dokku/postgres
#!/bin/bash
PGUSER=admin
PGHOST=db
EOF

cat<<EOF >> /etc/postgresql/9.1/main/pg_hba.conf
# Local administrative login via unix domain socket
local   all             git                                peer
# Network login for authenticated users
host    all             all             0.0.0.0/0          md5
EOF

sed -i "s/listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/9.1/main/postgresql.conf

service postgresql restart

sudo -u postgres createuser --createdb --createrole --superuser git || echo "Postgres git user creation failed"
sudo -u postgres createdb --owner=git git || echo "Postgres git DB creation failed"