#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/storage/functions"

storage_main_cmd() {
  declare desc="an alias for storage:list"
  local cmd="storage"

  dokku_log_warn "Deprecated: Please use storage:list"
  storage_list_cmd "$@"
}

storage_main_cmd "$@"
