#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/storage/functions"

storage_main_cmd() {
  declare desc="Display storage plugin help content"
  local cmd="storage"
  help_formatted
}

storage_main_cmd "$@"
