#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-pack-install() {
  declare desc="installs the builder-pack plugin"
  declare trigger="install"

  fn-plugin-property-setup "builder-pack"
}

trigger-builder-pack-install "$@"
