#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-builder-pack-post-delete() {
  declare desc="destroys the builder-pack properties for a given app"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "builder-pack" "$APP"
}

trigger-builder-pack-post-delete "$@"
