#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

ps_rebuildall_cmd() {
  declare desc="rebuilds all deployed apps via command line"
  local cmd="ps:rebuildall"
  for app in $(dokku_apps); do
    is_deployed "$app" && ps_rebuild "$app"
  done
}

ps_rebuildall_cmd "$@"
