#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

ps_rebuild_cmd() {
  local desc="rebuilds app via command line"
  local cmd="ps:rebuild"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  ps_rebuild "$2"
}

ps_rebuild_cmd "$@"
