#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/../functions"

shopt -s nullglob
for app in $DOKKU_ROOT/*/CONTAINER; do
  APP=$(basename "$(dirname $app)");
  dokku ps:rebuild $APP
done
