#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

cmd-ps-rebuild() {
  declare desc="rebuilds an app from source"
  declare cmd="ps:rebuild"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"

  if (is_deployed "$APP"); then
    ps_rebuild "$APP"
  else
    dokku_log_warn "App $APP has not been deployed"
  fi
}

cmd-ps-rebuild "$@"
