#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/internal-functions"

ps_rebuildall_cmd() {
  declare desc="rebuilds all apps from source"
  local cmd="ps:rebuildall"

  fn-ps-parallel-cmd "rebuild"
}

ps_rebuildall_cmd "$@"
