#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-ps-restart() {
  declare desc="restarts app via command line"
  declare cmd="ps:restart"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  plugn trigger app-restart "$APP"
}

cmd-ps-restart "$@"
