#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

ps_restore_cmd() {
  declare desc="starts all apps with DOKKU_APP_RESTORE not set to 0 via command line"
  local cmd="ps:restore"

  if which parallel > /dev/null 2>&1; then
    dokku_apps | parallel dokku ps:start
    return
  fi

  for app in $(dokku_apps); do
    local DOKKU_APP_RESTORE=$(config_get "$app" DOKKU_APP_RESTORE || true)
    if [[ $DOKKU_APP_RESTORE != 0 ]]; then
      echo "Restoring app $app ..."
      if ps_start "$app"; then
        continue
      fi
      dokku_log_warn "dokku ps:restore ${app} failed"
    fi
  done
}

ps_restore_cmd "$@"
