#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/internal-functions"

cmd-ps-restartall() {
  declare desc="restarts all apps via command line"
  declare cmd="ps:restartall"
  [[ "$1" == "$cmd" ]] && shift 1

  fn-ps-parallel-cmd "restart"
}

cmd-ps-restartall "$@"
