#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

cmd-ps-scale() {
  declare desc="sets app scaling config via command line"
  local cmd="ps:scale"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  shift 1
  ps_scale "$@"
}

cmd-ps-scale "$@"
