#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

cmd-ps-start() {
  declare desc="starts app via command line"
  declare cmd="ps:start"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  ps_start "$APP"
}

cmd-ps-start "$@"
