#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

ps_start_cmd() {
  declare desc="starts app via command line"
  local cmd="ps:start"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  ps_start "$2"
}

ps_start_cmd "$@"
