#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/internal-functions"

cmd-ps-startall() {
  declare desc="starts all apps via command line"
  declare cmd="ps:startall"
  [[ "$1" == "$cmd" ]] && shift 1

  fn-ps-parallel-cmd "start"
}

cmd-ps-startall "$@"
