#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$(dirname $0)/../functions"

[[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
verify_app_name "$2"

APP="$2"; [[ -f "$DOKKU_ROOT/$APP/CONTAINER" ]] && CONTAINER_ID=$(< "$DOKKU_ROOT/$APP/CONTAINER")
[[ -z "$CONTAINER_ID" ]] && echo "App $APP has not been deployed" && exit 0

if [[ "$(docker ps -q --no-trunc| grep -q $CONTAINER_ID; echo $?)" = "0" ]]; then
  echo "Stopping $APP ..."
  docker stop $CONTAINER_ID > /dev/null
else
  echo "App $APP already stopped"
fi
