#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/internal-functions"

cmd-ps-stopall() {
  declare desc="stops all apps via command line"
  declare cmd="ps:stopall"
  [[ "$1" == "$cmd" ]] && shift 1

  fn-ps-parallel-cmd "stop"
}

cmd-ps-stopall "$@"
