#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

nginx_build_config_cmd() {
  declare desc="build nginx config to proxy app containers from command line"
  local cmd="nginx:build-config"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  nginx_build_config "$2"
}

nginx_build_config_cmd "$@"
