#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

nginx_migrate_cmd() {
  declare desc="converts DOKKU_NGINX_* to DOKKI_PROXY_*"
  local cmd="nginx:migrate"
  migrate_nginx_to_proxy
}

nginx_migrate_cmd
