#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
shopt -s nullglob
VERSION="$1"
IMPORT_DIR="$2"
TARGET_DIR="$3"

cd $IMPORT_DIR

for file in */ssl/server.*; do
    mkdir -p $(dirname $TARGET_DIR$file)
    cp $file $TARGET_DIR$file
done
