#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"; IMAGE_SOURCE_TYPE="$2"

case "$0" in
  *docker-args-build)
    PHASE=BUILD
    ;;
  *docker-args-deploy)
    PHASE=DEPLOY
    ;;
  *docker-args-run)
    PHASE=RUN
    ;;
esac

FILE_PREFIX="DOCKER_OPTIONS_"
PHASE_FILE_PATH="${DOKKU_ROOT}/${APP}/${FILE_PREFIX}${PHASE}"

output=""

if [[ -f "$PHASE_FILE_PATH" ]]; then
  DONE=false
  until $DONE; do
    read -r line || DONE=true

    [[ ! -n "$line" ]] && continue

    # shellcheck disable=SC1001
    case "$line" in
      \#*)
        continue
        ;;
      *)
        case "$IMAGE_SOURCE_TYPE" in
          dockerfile)
            case "$line" in
              --link*|-v*)
                continue
                ;;

              *)
                output="$output $line"
                ;;
              esac
            ;;

          herokuish)
            case "$line" in
              --file*|--build-args*)
                continue
                ;;

              *)
                output="$output $line"
                ;;
              esac
            ;;

          *)
            output="$output $line"
            ;;
        esac
        ;;
    esac
  done < $PHASE_FILE_PATH
fi

echo "$STDIN$output"
