#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-docker-options-report() {
  declare desc="displays a docker options report for one or more apps"
  declare cmd="docker-options:report"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1" INFO_FLAG="$2"

  if [[ -n "$APP" ]] && [[ "$APP" == --* ]]; then
    INFO_FLAG="$APP"
    APP=""
  fi

  if [[ -z "$APP" ]] && [[ -z "$INFO_FLAG" ]]; then
    INFO_FLAG="true"
  fi

  if [[ -z "$APP" ]]; then
    for app in $(dokku_apps); do
      cmd-docker-options-report-single "$app" "$INFO_FLAG" | tee || true
    done
  else
    cmd-docker-options-report-single "$APP" "$INFO_FLAG"
  fi
}

cmd-docker-options-report-single() {
  declare APP="$1" INFO_FLAG="$2"
  if [[ "$INFO_FLAG" == "true" ]]; then
    INFO_FLAG=""
  fi
  verify_app_name "$APP"
  local flag_map=(
    "--docker-options-build: $(fn-docker-options "$APP" build)"
    "--docker-options-deploy: $(fn-docker-options "$APP" deploy)"
    "--docker-options-run: $(fn-docker-options "$APP" run)"
  )

  if [[ -z "$INFO_FLAG" ]]; then
    dokku_log_info2_quiet "$APP docker options information"
    for flag in "${flag_map[@]}"; do
      key="$(echo "${flag#--}" | cut -f1 -d' ' | tr - ' ')"
      dokku_log_verbose "$(printf "%-30s %-25s" "${key^}" "${flag#*: }")"
    done
  else
    local match=false
    local value_exists=false
    for flag in "${flag_map[@]}"; do
      valid_flags="${valid_flags} $(echo "$flag" | cut -d':' -f1)"
      if [[ "$flag" == "${INFO_FLAG}:"* ]]; then
        value=${flag#*: }
        size="${#value}"
        if [[ "$size" -ne 0 ]]; then
          echo "$value" && match=true && value_exists=true
        else
          match=true
        fi
      fi
    done
    [[ "$match" == "true" ]] || dokku_log_fail "Invalid flag passed, valid flags:${valid_flags}"
    echo ""
  fi
}

fn-docker-options() {
  declare APP="$1" PHASE="$2"
  local PHASE_FILE="$(fn-get-phase-file-path "$APP" "$PHASE")"
  if [[ -r "$PHASE_FILE" ]]; then
    tr '\n' ' ' <"$PHASE_FILE"
  fi
}
