SUBCOMMANDS = subcommands/add subcommands/clear subcommands/remove subcommands/report
TRIGGERS = triggers/post-app-clone-setup triggers/post-app-rename-setup triggers/post-delete triggers/report
BUILD = commands subcommands triggers
PLUGIN_NAME = docker-options

include ../../common.mk
