SUBCOMMANDS = subcommands/add subcommands/clear subcommands/list subcommands/remove subcommands/report
TRIGGERS = triggers/docker-args-build triggers/docker-args-deploy triggers/docker-args-process-deploy triggers/docker-args-run triggers/install triggers/post-app-clone-setup triggers/post-app-rename-setup triggers/post-delete triggers/report
BUILD = commands subcommands triggers
PLUGIN_NAME = docker-options

include ../../common.mk
