#!/bin/bash

exec >> /var/log/services/dokku-restore
exec 2>&1

if [[ "$1" -ne 0 ]]; then
  echo "Error initializing dokku! Retrying in 30 seconds..."
  exec sleep 30
  exit 0
fi

echo "Done initializing dokku."
exec sleep infinity

exit 0
