#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/command-functions"
source "$PLUGIN_AVAILABLE_PATH/openresty-vhosts/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-openresty-labels-add() {
  declare desc="adds container label to app for specified proxy"
  declare cmd="openresty:labels:add"
  [[ "$1" == "$cmd" ]] && shift 1

  cmd-proxy-labels-add "proxy:labels:add" "openresty" "$@"
}

cmd-openresty-labels-remove() {
  declare desc="removes container label from app for specified proxy"
  declare cmd="openresty:labels:remove"
  [[ "$1" == "$cmd" ]] && shift 1

  cmd-proxy-labels-remove "proxy:labels:remove" "openresty" "$@"
}

cmd-openresty-labels-show() {
  declare desc="shows container labels for app for specified proxy"
  declare cmd="openresty:labels:show"
  [[ "$1" == "$cmd" ]] && shift 1

  cmd-proxy-labels-show "proxy:labels:show" "openresty" "$@"
}

cmd-openresty-logs() {
  declare desc="display openresty logs from command line"
  declare cmd="openresty:logs"
  [[ "$1" == "$cmd" ]] && shift 1
  local NUM="100" TAIL=false

  local TEMP=$(getopt -o htn: --long help,tail,num: -n 'dokku openresty:logs' -- "$@")
  local EXIT_CODE="$?"
  if [[ "$EXIT_CODE" != 0 ]]; then
    fn-openresty-logs-usage >&2
    exit 1
  fi
  eval set -- "$TEMP"

  while true; do
    case "$1" in
      -t | --tail)
        local TAIL=true
        shift
        ;;
      -n | --num)
        local NUM="$2"
        shift 2
        ;;
      --)
        shift
        break
        ;;
      *) dokku_log_fail "Internal error" ;;
    esac
  done

  fn-openresty-logs "$TAIL" "$NUM"
}

cmd-openresty-show-config() {
  declare desc="display openresty config"
  declare cmd="openresty:show-config"
  [[ "$1" == "$cmd" ]] && shift 1

  if ! fn-is-compose-installed; then
    dokku_log_fail "Required docker compose plugin is not installed"
  fi

  local TMP_COMPOSE_FILE=$(mktemp "/tmp/dokku-${DOKKU_PID}-${FUNCNAME[0]}.XXXXXX")
  trap "rm -rf '$TMP_COMPOSE_FILE' >/dev/null" RETURN INT TERM EXIT

  fn-openresty-template-compose-file "$TMP_COMPOSE_FILE"
  cat "$TMP_COMPOSE_FILE"
}

cmd-openresty-start() {
  declare desc="Starts the openresty server"
  declare cmd="openresty:start"
  [[ "$1" == "$cmd" ]] && shift 1

  if ! fn-is-compose-installed; then
    dokku_log_fail "Required docker compose plugin is not installed"
  fi

  local TMP_COMPOSE_FILE=$(mktemp "/tmp/dokku-${DOKKU_PID}-${FUNCNAME[0]}.XXXXXX")
  trap "rm -rf '$TMP_COMPOSE_FILE' >/dev/null" RETURN INT TERM EXIT

  fn-plugin-property-write "openresty" "--global" "proxy-status" "started"
  fn-openresty-template-compose-file "$TMP_COMPOSE_FILE"
  if ! "$PLUGIN_CORE_AVAILABLE_PATH/common/common" compose-up "openresty" "$TMP_COMPOSE_FILE"; then
    return 1
  fi
}

cmd-openresty-stop() {
  declare desc="Starts the openresty server"
  declare cmd="openresty:stop"
  [[ "$1" == "$cmd" ]] && shift 1

  if ! fn-is-compose-installed; then
    dokku_log_fail "Required docker compose plugin is not installed"
  fi

  local TMP_COMPOSE_FILE=$(mktemp "/tmp/dokku-${DOKKU_PID}-${FUNCNAME[0]}.XXXXXX")
  trap "rm -rf '$TMP_COMPOSE_FILE' >/dev/null" RETURN INT TERM EXIT

  fn-plugin-property-write "openresty" "--global" "proxy-status" "stopped"
  fn-openresty-template-compose-file "$TMP_COMPOSE_FILE"
  if ! "$PLUGIN_CORE_AVAILABLE_PATH/common/common" compose-down "openresty" "$TMP_COMPOSE_FILE"; then
    return 1
  fi
}
