#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/openresty-vhosts/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

fn-openresty-vhosts-copy-from-image() {
  declare APP="$1" IMAGE_NAME="$2" CONF_PATH="$3"

  mkdir -p "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP"
  find "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/" -maxdepth 1 -name 'openresty-http-includes.*' -type d -exec rm -r {} +
  copy_dir_from_image "$IMAGE_NAME" "$CONF_PATH" "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID" || true
  if [[ ! -f "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID" ]]; then
    touch "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID.missing"
  fi
}

fn-openresty-vhosts-copy-from-directory() {
  declare APP="$1" SOURCECODE_WORK_DIR="$2" CONF_PATH="$3"

  pushd "$SOURCECODE_WORK_DIR" >/dev/null
  mkdir -p "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP"

  if [[ -z "$CONF_PATH" ]]; then
    touch "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID.missing"
    return
  fi

  if [[ ! -d "$CONF_PATH" ]]; then
    touch "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID.missing"
    return
  fi

  find "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/" -maxdepth 1 -name 'openresty-http-includes.*' -type d -exec rm -r {} +
  mkdir p "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID/"
  cp -f "$CONF_PATH"/* "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID/"
  popd &>/dev/null || pushd "/tmp" >/dev/null
}

trigger-openresty-vhosts-core-post-extract() {
  declare desc="openresty-vhosts post-extract plugin trigger"
  declare trigger="post-extract"
  declare APP="$1" SOURCECODE_WORK_DIR="$2"
  local CONF_PATH="openresty-http-includes"
  local app_source_image

  app_source_image="$(plugn trigger git-get-property "$APP" "source-image")"
  if [[ -n "$app_source_image" ]]; then
    fn-openresty-vhosts-copy-from-image "$APP" "$app_source_image" "$CONF_PATH"
  else
    fn-openresty-vhosts-copy-from-directory "$APP" "$SOURCECODE_WORK_DIR" "$CONF_PATH"
  fi
}

trigger-openresty-vhosts-core-post-extract "$@"
