#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/openresty-vhosts/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-openresty-vhosts-core-post-deploy() {
  declare desc="openresty-vhosts core-post-deploy plugin trigger"
  declare trigger="core-post-deploy"
  declare APP="$1"
  local tls_internal

  if [[ "$(plugn trigger proxy-type "$APP")" != "openresty" ]]; then
    return
  fi

  dokku_log_info1 "Routing app via openresty"
  if [[ -f "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID.missing" ]]; then
    rm -f "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes.$DOKKU_PID.missing"
    rm -f "${DOKKU_LIB_ROOT}/data/openresty-vhosts/app-$APP/openresty-http-includes"
  fi
}

trigger-openresty-vhosts-core-post-deploy "$@"
