#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-openresty-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="openresty"
  local plugin_description="Manage the openresty proxy integration"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    openresty:report [<app>] [<flag>], Displays an openresty report for one or more apps
    openresty:set <app> <property> (<value>), Set or clear an openresty property for an app
    openresty:show-config <app>, Display openresty compose config
    openresty:label <app> <show | set | unset> <property> (<value>), Show, set or clear an openresty label for an app
    openresty:start, Starts the openresty server
    openresty:stop, Stops the openresty server
help_content
}
