#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

trigger-openresty-vhosts-post-app-clone-setup() {
  declare desc="removes openresty files when setting up a clone"
  declare trigger="post-app-clone-setup"
  declare OLD_APP="$1" NEW_APP="$2"
  local APP_ROOT="$DOKKU_ROOT/$NEW_APP"

  fn-plugin-property-clone "openresty" "$OLD_APP" "$NEW_APP"
}

trigger-openresty-vhosts-post-app-clone-setup "$@"
