#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/openresty-vhosts/command-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-openresty-pre-restore() {
  declare desc="pre-restore the openresty proxy"
  declare trigger="install"

  if [[ "$(fn-plugin-property-get "openresty" "--global" "proxy-status")" != "started" ]]; then
    return
  fi

  if ! cmd-openresty-start; then
    dokku_log_warn "Failed to restore openresty proxy, requests may not route as expected"
  fi
}

trigger-openresty-pre-restore "$@"
